<?php $perfil = Zend_Auth::getInstance()->getIdentity()->perfilid; ?>
<h3>Pesquisar produto por categoria</h3>
<hr>
<div class="instrucao">
    <p>Escolha uma das categorias cadastradas abaixo para listar seus produtos:</p>

    <div class="combobox">
        <form class="form-horizontal" action="<?= $this->baseUrl() . '/produto/buscarprodutoporcategoria' ?>" method="POST">
            <select required="true" name="categoriaid">
                <option value="">--selecione--</option>
                <?php foreach ($this->listadecategorias as $nomeCategoria): ?>
                    <option required="true" value="<?php echo $nomeCategoria['id']; ?>"><?php echo $nomeCategoria['nome']; ?></option>
                    <?php
                endforeach;
                ?>
            </select>
            <button class="btn btn-primary btn-filter btn-sm"><span class="glyphicon glyphicon-search"></span> Pesquisar</button>
        </form>
    </div>
</div>
<?php if ($this->listaDeProdutos) { ?>
    <div class="row">
        <div class="panel panel-primary filterable conteudogerente">
            <div class="panel-heading">
                <div class="pull-right">
                    <button class="btn btn-default btn-xs btn-filter"><span class="glyphicon glyphicon-filter"></span> Buscar na lista</button>
                </div>
                <span class="glyphicon glyphicon-list"></span> Lista de produtos da categoria <strong><?php echo $nomeCategoria['nome']; ?></strong>
            </div>
            <form action="<?= $this->baseUrl() . '/produtosolicitacao/inserir' ?>" method="POST">
                <table class="table table-striped table-hover tabela-busca">
                    <thead>
                        <tr class="filters">
                            <th><input type="text" class="form-control" placeholder="Produto" disabled></th>
                            <th><input type="text" class="form-control" placeholder="Categoria" disabled></th>
                            <th><input type="text" class="form-control" placeholder="Descrição" disabled></th>
                            <th><input type="text" class="form-control" placeholder="Quantidade" disabled></th>
                             <?php if (($perfil == 2) || ($perfil == 3)) { ?>
                                <th></th>
                            <?php } ?>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($this->listaDeProdutos as $produto) { ?>
                            <tr>
                                <?php
                                $tCategoria = new Categoria();
                                $categoriaNome = $tCategoria->findCategoriaById($produto['categoriaid']);
                                ?>
                        <input type="hidden" name="categoriaid" value="<?php echo $produto['categoriaid'] ?>">
                        <td><?= $produto['nome']; ?></td>
                        <td><?= $categoriaNome[0]->nome; ?></td>
                        <td><?= $produto['descricao']; ?></td>
                        <?php if ($produto['quantidade'] == 0) { ?>
                            <td><a class='btn btn-info btn-xs' href="<?php echo $this->url(array('controller' => 'solicitacao', 'action' => 'inserirsolicitacaoagendada', 'produtoid' => $produto['id'])); ?>"><span class="glyphicon glyphicon-time"></span> Agendar</a></td>
                        <?php } else {
                            ?>
                            <td> <?= $produto['quantidade']; ?></td>
                        <?php } ?>
                        <?php if (($perfil == 2) || ($perfil == 3)) { ?>
                        <td><a class='btn btn-block btn-warning btn-xs' href="<?php echo $this->url(array('controller' => 'produto', 'action' => 'editar', 'id' => $produto['id'])); ?>"><span class="glyphicon glyphicon-edit"></span> Editar</a></td>
                        <td class="text-center"><a href="<?php echo $this->url(array('controller' => 'produto', 'action' => 'deletar', 'id' => $produto['id'])); ?>" class="btn btn-danger btn-block btn-xs"><span class="glyphicon glyphicon-remove-circle"></span>Excluir</a></td>
                            <?php } ?>
                        </tr>
                    <?php }
                }
                ?>
                </tbody>
            </table>
        </form>
    </div>
</div>


