<form class="form-horizontal" action="<?= $this->baseUrl() . '/produto/editar' ?>" method="POST">
    <input type="hidden" name="id" value="<?php echo $this->produto->id ?>">
    <fieldset>
        <legend>Editar produto</legend>
        <div class="form-group">
            <label for="inputCategoria" class="col-md-4 control-label">Categoria</label>
            <div class="col-md-6">
                <div class="form-group">
                    <div class="col-md-6">
                        
                        <?php $tCategoria = new DbTable_Categoria();
                              $categoria = $tCategoria->find($this->produto->categoriaid)->current();
                              $nomeCategoria = $categoria->nome;
                        ?>
                        <input class="form-control" id="inputNome" readonly="true" placeholder="" type="text" name="categoria" required="true" value="<?php echo $nomeCategoria ?>"> 
                    </div>
                </div>
            </div>
            <div class="form-group">
                <label for="inputNome" class="col-md-4 control-label">Nome</label>
                <div class="col-md-6">
                    <input class="form-control" id="inputNome" placeholder="" type="text" name="nome" required="true" value="<?php echo $this->produto->nome ?>"> 
                </div>
            </div>
            <div class="form-group">
                <label for="Descrição" class="col-md-4 control-label">Descrição</label>
                <div class="col-md-6">
                    <textarea class="form-control" rows="3" id="descricao" name="descricao"><?php echo $this->produto->descricao ?></textarea>
                    <span class="help-block">Faça uma breve descrição sobre o produto a ser criado</span>
                </div>
            </div>
            <div class="form-group">
                <label for="inputValidade" class="col-md-4 control-label">Validade</label>
                <div class="col-md-3">
                    <input class="form-control" id="inputValidade" placeholder="" type="date" name="validade" value="<?php echo $this->produto->validade ?>">
                    <span class="help-block">Preencha se for necessário</span>
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-6 col-md-offset-6">
                    <a class="btn btn-primary" href="<?php echo $this->url(array('controller' => 'categoria', 'action' => 'selecionarcategoria')); ?>">Voltar</a>
                    <button type="submit" class="btn btn-success">Editar</button>
                </div>
            </div>
    </fieldset>
</form>