<form class="form-horizontal" action="<?= $this->baseUrl() . '/produto/editar' ?>" method="POST">
    <input type="hidden" name="id" value="<?php echo $this->produto->id?>">
    <fieldset>
        <legend>Editar produto</legend>
        <div class="form-group">
            <label for="select" class="col-lg-4 control-label">Categoria</label>
            <div class="col-lg-2">
                <select required = "true" class="form-control" id="select" name="categoriaid" required="true">
                    <option value="">--selecione--</option>
                    <?php foreach ($this->categorias as $nomeCategoria): ?> 
                        <option value="<?php echo $nomeCategoria['id']; ?>"><?php echo $nomeCategoria['nome']; ?></option>
                    <?php
                    endforeach;
                    ?> 
                </select>     
                <br>
            </div>
        </div>
        <div class="form-group">
            <label for="inputNome" class="col-lg-4 control-label">Nome</label>
            <div class="col-lg-6">
                <input class="form-control" id="inputNome" placeholder="" type="text" name="nome" required="true" value="<?php echo $this->produto->nome?>"> 
            </div>
        </div>
        <div class="form-group">
            <label for="Descrição" class="col-lg-4 control-label">Descrição</label>
            <div class="col-lg-6">
                <textarea class="form-control" rows="3" id="descricao" name="descricao"><?php echo $this->produto->descricao?></textarea>
                <span class="help-block">Faça uma breve descrição sobre o perfil a ser criado</span>
            </div>
        </div>
        <div class="form-group">
            <label for="inputQuantidade" class="col-lg-4 control-label" >Quantidade</label>
            <div class="col-lg-2">
                <input class="form-control" required="true" id="quantidade" placeholder="" type="number" min="1" name="quantidade" value="<?php echo $this->produto->quantidade?>">
            </div>
        </div>
        <div class="form-group">
            <label for="inputQuantidademinima" class="col-lg-4 control-label" >Quantidade mínima</label>
            <div class="col-lg-2">
                <input class="form-control" required="true" id="quantidademinima" placeholder="" type="number" min="1" name="quantidademinima" value="<?php echo $this->produto->quantidademinima?>">
                <span class="help-block">Quantidade para reposição</span>
            </div>
        </div>
        <div class="form-group">
            <label for="inputValidade" class="col-lg-4 control-label">Validade</label>
            <div class="col-lg-2">
                <input class="form-control" id="inputValidade" placeholder="" type="date" name="validade" value="<?php echo $this->produto->validade?>">
                <span class="help-block">Preencha se for necessário</span>
            </div>
        </div>
        <div class="form-group">
      <div class="col-lg-6 col-lg-offset-6">
        <a class="btn btn-primary" href="<?php echo $this->url(array('controller' => 'categoria', 'action' => 'selecionarcategoria')); ?>">Voltar</a>
        <button type="submit" class="btn btn-success">Editar</button>
      </div>
    </div>
    </fieldset>
</form>