<form class="form-horizontal" action="<?= $this->baseUrl() . '/produto/inserir' ?>" method="POST">
    <fieldset>
        <legend>Criar produto</legend>
        <div class="form-group">
            <label for="select" class="col-lg-4 control-label">Categoria</label>
            <div class="col-lg-2">
                <select class="form-control" id="select" name="categoriaid" required="true">
                    <option selected disabled value=""></option>
                    <?php foreach ($this->categorias as $nomeCategoria): ?> 
                        <option value="<?php echo $nomeCategoria['id']; ?>"><?php echo $nomeCategoria['nome']; ?></option> 
                    <?php
                    endforeach;
                    ?> 
                </select>     
                <br>
            </div>
        </div>
        <div class="form-group">
            <label for="inputNome" class="col-lg-4 control-label">Nome</label>
            <div class="col-lg-6">
                <input class="form-control" id="inputNome" placeholder="" type="text" name="nome">
            </div>
        </div>
        <div class="form-group">
            <label for="Descrição" class="col-lg-4 control-label">Descrição</label>
            <div class="col-lg-6">
                <textarea class="form-control" rows="3" id="descricao" name="descricao"></textarea>
                <span class="help-block">Faça uma breve descrição sobre o perfil a ser criado</span>
            </div>
        </div>
        <div class="form-group">
            <label for="inputQuantidade" class="col-lg-4 control-label">Quantidade</label>
            <div class="col-lg-3">
                <input class="form-control" id="quantidade" placeholder="" type="number" min="1" name="quantidade">
            </div>
        </div>
        <div class="form-group">
            <label for="inputQuantidademinima" class="col-lg-4 control-label" >Quantidade mínima</label>
            <div class="col-lg-3">
                <input class="form-control" id="quantidademinima" placeholder="" type="text" name="quantidademinima">
                <span class="help-block">Informativo para reposição de estoque</span>
            </div>
        </div>
        <div class="form-group">
            <label for="inputValidade" class="col-lg-4 control-label">Validade</label>
            <div class="col-lg-4">
                <input class="form-control" id="inputValidade" placeholder="" type="date" name="validade">
                <span class="help-block">Preencha se for necessário</span>
            </div>
        </div>
        <div class="form-group">
            <div class="col-lg-6 col-lg-offset-6">
                <button type="submit" class="btn btn-primary" id="enviar">Inserir</button>
            </div>
        </div>
    </fieldset>
</form>