<center>
    <h1 class="print">Prefeitura do Estado do Rio de Janeiro</h1>
    <h2 class="print">Centro Integrado de Educação Pública (CIEP) Almir Bonfim de Andrade </h2>
    <h3>Relatório de produtos indisponíveis</h3>
</center>
<?php if ($this->produtos <> null) { ?>
    <p> Abaixo segue o resultado de sua busca. </p>
<?php } else { ?>
    <p> Não existe produtos indisponíveis em estoque, porisso seu relatório encontra-se vazio.</p>
<?php } ?>
<hr>
<div class="panel panel-primary filterable"> 
    <div class="panel-heading">
        <div class="pull-right">
            <button class="btn btn-default btn-xs btn-filter no-print"><span class="glyphicon glyphicon-filter"></span> Buscar na lista</button>
            <button class="btn btn-default btn-xs btn-primary imprimir no-print"><span class="glyphicon glyphicon-print"></span> Imprimir</button>
        </div>
        <span class="glyphicon glyphicon-list"></span> Relatório de produtos indisponíveis
    </div>
    <div class="panel-body">
        <table class="table table-striped table-hover tabela-busca"> 
            <thead>             
                <tr class="filters">
                    <th><input type="text" class="form-control" placeholder="Nome" disabled></th>
                    <th><input type="text" class="form-control" placeholder="Descrição" disabled></th>
                    <th><input type="text" class="form-control" placeholder="Quantidade" disabled></th>
                    <th><input type="text" class="form-control" placeholder="Quantidade mínima" disabled></th>
                </tr>
            </thead>
            <?php foreach ($this->lisdaDeIndisponiveis as $produto) { ?>
                <tr>
                    <td class="text-left"><?= $produto['nome']; ?></td>
                    <td class="text-left"><?= $produto['descricao']; ?></td>
                    <td class="text-left"><?= $produto['quantidade']; ?></td>
                    <td class="text-left"><?= $produto['quantidademinima']; ?></td>
                </tr>     
            <?php } ?>      
        </table>
    </div>
</div>
