<legend>Produtos indisponíveis em estoque</legend>
<hr>
<div class="panel panel-primary"> 
    <div class="panel-heading" id="actions"><span class="glyphicon glyphicon-list"></span> Relatório de produtos indisponíveis
        <a href="<?php echo $this->url(array('controller' => 'categoria', 'action' => 'inserir')); ?>" class="btn btn-info btn-xs pull-right" style="border:2"><span class="glyphicon glyphicon-plus"></span>Nova categoria</a>
    </div>
    <div class="panel-body">
        <table class="table table-striped table-hover"> 
            <thead>             
                <tr>
                    <th>Nome</th>
                    <th>Descrição</th>
                    <th>Quantidade</th>
                    <th>Quantidade mínima</th>
                </tr>
            </thead>
            <?php foreach ($this->lisdaDeIndisponiveis as $produto) { ?>
                <tr>
                    <td><?= $produto['nome']; ?></td>
                    <td><?= $produto['descricao']; ?></td>
                    <td><?= $produto['quantidade']; ?></td>
                    <td><?= $produto['quantidademinima']; ?></td>
                </tr>     
            <?php } ?>      
        </table>
    </div>
</div>
