    <h3>Lista de Produtos</h3>
    <hr>
    <p>Selecione os produtos que desejar e mova-os para a <a href="http://bootsnipp.com/snippets/featured/panel-tables-with-filter">caixa de solicitações <span class="glyphicon glyphicon-shopping-cart"></span></a></p>
    <div class="row">
        <div class="panel panel-primary filterable">
            <div class="panel-heading">
                <div class="pull-right">
                    <button class="btn btn-default btn-xs btn-filter"><span class="glyphicon glyphicon-filter"></span> Buscar na lista</button>
                </div>
                <span class="glyphicon glyphicon-list"></span>Lista de produtos
            </div>
            <table class="table">
                <thead>
                <tr class="filters">
                    <th><input type="text" class="form-control" placeholder="Produto" disabled></th>
                    <th><input type="text" class="form-control" placeholder="Categoria" disabled></th>
                    <th><input type="text" class="form-control" placeholder="Descrição" disabled></th>
                    <th><input type="text" class="form-control" placeholder="Quantidade em estoque" disabled></th>
                    <th><input type="text" class="form-control" placeholder="Quantidade Mínima" disabled></th>
                    <th style="width: 200px;"><center>Ação</center></th>
                </tr>
                </thead>
                <tbody>
                <tr>
                     <?php foreach ($this->listaDeProdutos as $produto) { ?>
                    <?php
                    $tCategoria = new Categoria();
                    $categoriaNome = $tCategoria->findCategoriaById($produto['categoriaid']);
                    ?>
                    <td><?= $produto['nome']; ?></td>
                    <td><?= $categoriaNome['nome']->nome; ?></td>
                    <td><?= $produto['descricao']; ?></td>
                    <td><?= $produto['quantidade']; ?></td>
                    <td><?= $produto['quantidademinima']; ?></td>
                    <td class="text-center" style="width: 150px;"><a class='btn btn-info btn-xs' href="<?php echo $this->url(array('controller' => 'produto', 'action' => 'editar', 'id' => $produto['id'])); ?>"><span class="glyphicon glyphicon-edit"></span>Editar</a> <a href="<?php echo $this->url(array('controller' => 'produto', 'action' => 'deletar', 'id' => $produto['id'])); ?>" class="btn btn-danger btn-xs"><span class="glyphicon glyphicon-remove"></span>Deletar</a></td>
                </tr>     
            <?php } ?>     
                </tbody>
            </table>
        </div>
    </div>
