<legend>Produtos com quantidade mínima atingida</legend>
<hr>
<div class="panel panel-primary"> 
    <div class="panel-heading" id="actions"><span class="glyphicon glyphicon-list"></span> Relatório de produtos com quantidade mínima atingida
    </div>
    <div class="panel-body">
        <table class="table table-striped table-hover"> 
            <thead>             
                <tr>
                    <th>Nome</th>
                    <th>Descrição</th>
                    <th>Quantidade</th>
                    <th>Quantidade mínima</th>
                </tr>
            </thead>
            <?php foreach ($this->lisdaDeQuantidadeMinima as $produto) { ?>
                <tr>
                    <td><?= $produto['nome']; ?></td>
                    <td><?= $produto['descricao']; ?></td>
                    <td><?= $produto['quantidade']; ?></td>
                    <td><?= $produto['quantidademinima']; ?></td>
                </tr>     
            <?php } ?>      
        </table>
    </div>
</div>
