<?php ?>
<form class="form-horizontal" action="<?= $this->baseUrl() . '/usuario/editar' ?>" method="POST">
    <fieldset>
        <legend>Editar usuário</legend>   
        <input type="hidden" name="id" value="<?php echo $this->usuario->id ?>">
        <div class="form-group">
            <label for="" class="col-md-4 control-label">Funcionário</label>
            <div class="col-md-6">
                <?php $tPessoa = new DbTable_Pessoa(); 
                $pessoa = $tPessoa->find($this->usuario->pessoaid)->current();
                $pessoaNome = $pessoa->nome;?>
                <input class="form-control" id="inputLogin" readonly="true" placeholder="" type="text" name="pessoa" value="<?php echo $pessoaNome ?>">
            </div>
        </div>
        <div class="form-group">
            <label for="inputLogin" class="col-md-4 control-label">Perfil</label>
            <div class="col-md-6">
                <?php $tPerfil = new DbTable_Perfil(); 
                $perfil = $tPerfil->find($this->usuario->perfilid)->current();
                $perfilNome = $perfil->nome;?>
                <input class="form-control" id="inputLogin" readonly="true" placeholder="" type="text" name="pessoa" value="<?php echo $perfilNome ?>">
            </div>
        </div>
        <div class="form-group">
            <label for="inputLogin" class="col-md-6 control-label">Login</label>
            <div class="col-md-2">
                <input class="form-control" id="inputLogin" placeholder="" type="text" name="login" value="<?php echo $this->usuario->login ?>">
            </div>
        </div>
        <div class="form-group">
            <label for="inputSenha" class="col-md-6 control-label">Senha</label>
            <div class="col-md-2">
                <input class="form-control" id="inputSenha" placeholder="" type="password" name="senha">
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-6 col-md-offset-6">
                <!-- <button class="btn btn-default">Cancelar</button>-->
                <a class="btn btn-primary" href="<?php echo $this->url(array('controller' => 'usuario', 'action' => 'listar')); ?>">Voltar</a>
                <button type="submit" class="btn btn-success">Editar</button>
            </div>
        </div>
    </fieldset>
</form>