<form class="form-horizontal" action="<?= $this->baseUrl() . '/usuario/inserir' ?>" method="POST">
    <fieldset>
        <legend>Criando novo usuário</legend>        
        <div class="form-group">
            <label for="select" class="col-md-4 control-label">Funcionário</label>
            <div class="col-md-6">
                <select required="true" class="form-control" id="select" name="pessoaid">
                    <option value="">--selecione--</option>
                    <?php foreach ($this->pessoas as $nomePessoa): ?> 
                        <option value="<?php echo $nomePessoa['id']; ?>"><?php echo $nomePessoa['nome']; ?></option> 
                        <?php
                    endforeach;
                    ?> 
                </select>   
                <span class="help-block">O funcionário precisa estar cadastrado</span>
                <br>
            </div>
        </div>
        <div class="form-group">
            <label for="select" class="col-md-4 control-label">Perfil</label>
            <div class="col-md-6">
                <select required="true" class="form-control" id="select" name="perfilid">
                    <option value="">--selecione--</option>
                    <?php foreach ($this->perfis as $nomePerfil): ?> 
                        <option value="<?php echo $nomePerfil['id']; ?>"><?php echo $nomePerfil['nome']; ?></option> 
                        <?php
                    endforeach;
                    ?> 
                </select>   
                <span class="help-block">Perfil dá permissões de acesso ao usuário</span>
                <br>
            </div>
        </div>
        <div class="form-group">
            <label for="inputLogin" class="col-md-6 control-label">Login</label>
            <div class="col-md-2">
                <input class="form-control" id="inputLogin" placeholder="" type="text" name="login">
            </div>
        </div>
        <div class="form-group">
            <label for="inputSenha" class="col-md-6 control-label">Senha</label>
            <div class="col-md-2">
                <input class="form-control" id="inputSenha" placeholder="" type="password" name="senha">
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-6 col-md-offset-6">
                <!-- <button class="btn btn-default">Cancelar</button>-->
                <a class="btn btn-primary" href="<?php echo $this->url(array('controller' => 'usuario', 'action' => 'listar')); ?>">Voltar</a>
                <button type="submit" class="btn btn-success">Inserir</button>
            </div>
        </div>
    </fieldset>
</form>