<div class="panel "> <div class="panel-heading panel-primary">
        <div id="actions">
            <a href="<?php echo $this->url(array('controller' => 'usuario', 'action' => 'inserir')); ?>" class="btn btn-primary btn-xs pull left"><b>+</b>Novo usuário</a>
        </div>                
        <center><h3 class="panel-title">>> Lista de solicitações ativas <<</h3></center>
    </div>
    <div class="panel-body">
        <table class="table table-striped table-hover"> 
            <thead>
                <tr>
                    <th>Login</th>
                    <th>Funcionário</th>
                    <th>Perfil</th>
                    <th class="text-center">Ação</th>
                </tr>
            </thead>
            <tr>
                <?php
                foreach ($this->listaDeUsuarios as $usuario) {
                    $tPessoa = new Pessoa();
                    $pessoaNome = $tPessoa->findPessoaById($usuario['pessoaid']);

                    $tPerfil = new Perfil();
                    $perfilNome = $tPerfil->findPerfilById($usuario['perfilid']);
                    ?>
                    <td><?= $usuario['login']; ?></td>
                    <td><?= $pessoaNome['nome']->nome; ?></td>
                    <td><?= $perfilNome['nome']->nome; ?></td>
                    <td class="text-center"><a class='btn btn-info btn-xs' href="<?php echo $this->url(array('controller' => 'usuario', 'action' => 'editar', 'id' => $usuario['id'])); ?>"><span class="glyphicon glyphicon-edit"></span>Editar</a>
                        <a href="<?php echo $this->url(array('controller' => 'usuario', 'action' => 'deletar', 'id' => $usuario['id'])); ?>" class="btn btn-danger btn-xs"><span class="glyphicon glyphicon-remove"></span>Deletar</a>
                    </td>
                </tr>     
<?php } ?>      
        </table>
    </div>
</div>
