<legend>Usuários cadastrados</legend>
<hr>
<div class="panel panel-primary"> 

   <div class="panel-heading" id="actions"><span class="glyphicon glyphicon-list"></span> Lista de usuários existentes
      <a href="<?php echo $this->url(array('controller' => 'usuario', 'action' => 'inserir')); ?>" class="btn btn-info btn-xs pull-right" style="border:2"><span class="glyphicon glyphicon-plus"></span>Novo usuário</a>
   </div>

    <div class="panel-body">
        <table class="table table-striped table-hover"> 
            <thead>
                <tr>
                    <th>Login</th>
                    <th>Funcionário</th>
                    <th>Perfil</th>
                    <th></th>
                    <th></th>
                    <?php if ($this->relatorio <> null)?>
                    <th></th>
                </tr>
            </thead>
            <tr>
                <?php
                foreach ($this->listaDeUsuarios as $usuario) {
                    
                    $tPessoa = new Pessoa();
                    $pessoaNome = $tPessoa->findPessoaById($usuario['pessoaid'])->current();
                    

                    $tPerfil = new Perfil();
                    $perfilNome = $tPerfil->findPerfilById($usuario['perfilid'])->current();
                    ?>
                    <td><?= $usuario['login']; ?></td>
                    <td><?= $pessoaNome->nome; ?></td>
                    <td><?= $perfilNome->nome; ?></td>
                    <td class="text-center"><a class='btn btn-block btn-warning btn-xs' href="<?php echo $this->url(array('controller' => 'usuario', 'action' => 'editar', 'id' => $usuario['id'])); ?>"><span class="glyphicon glyphicon-edit"></span> Editar</a></td>
                        <td class="text-center"><a href="<?php echo $this->url(array('controller' => 'usuario', 'action' => 'deletar', 'id' => $usuario['id'])); ?>" class="btn btn-block btn-danger btn-xs"><span class="glyphicon glyphicon-remove-circle"></span> Excluir</a></td>
                    <?php if ($this->relatorio <> null){?>
                    <td class="text-center"><a class='btn btn-block btn-primary btn-xs' href="<?php echo $this->url(array('controller' => 'relatorio', 'action' => 'solicitacoesporusuario', 'usuarioid' => $usuario['id'], 'login' => $usuario['login'])); ?>"><span class="glyphicon glyphicon-edit"></span> Selecionar</a></td>
                    <?php } ?>
                </tr>     
      <?php } ?>
        </table>
    </div>
</div>
