<h3>Entrega parcial de item</h3>
<hr>
<div class="instrucao">
    <p>Insira a quantidade que deseja repor no estoque e informe uma observação se achar necessário</p>
    <form class="form-horizontal" action="" method="POST">
        <input type="hidden" name="produtoid" value="<?php echo $this->produtoid ?>">
        <input type="hidden" name="compraid" value="<?php echo $this->compraid ?>">
        <br><br>
            <div class="form-group">
            <label for="quantidade" class="col-md-4 control-label">Quantidade</label>
            <div class="col-md-3">
                <input class="form-control" type="number" required="true" name="quantidade" placeholder="Repor no estoque">    
            </div>
        </div>    
        <div class="form-group">
            <div class="col-md-4 col-md-offset-4">
                <button type="submit" class="btn btn-success btn-block"><span class="glyphicon glyphicon-folder-close"></span> Atualizar estoque</button>
            </div>
        </div>
    </form>

</div>








