<legend>Fornecedores cadastrados</legend>
<hr>
<div class="panel panel-primary"> 

    <div class="panel-heading" id="actions"><span class="glyphicon glyphicon-list"></span> Lista de fornecedores cadastrados</div>
    <div class="panel-body">
        <table class="table table-striped table-hover tabela-fornecedor"> 
            <?php if (empty($this->listaDeFornecedores[0])) { ?>
                <center><strong><h4>sem fornecedor cadastrado</h4></strong></center>
                </tr>
            <?php } else { ?>
                <thead>
                    <tr>
                        <th>Razão Social</th>
                        <th>Telefone principal</th>
                        <th>Outro contato</th>
                        <th>Bairro</th>
                        <th>Cidade</th>
                        <th>Contato</th>
                        <th>Email</th>
                    </tr>
                </thead>

                <?php foreach ($this->listaDeFornecedores as $fornecedor) { ?>
                    <tr>
                        <td><?= $fornecedor['razao_social']; ?></td>
                        <td><?= $fornecedor['telefone1']; ?></td>
                        <td><?= $fornecedor['telefone2']; ?></td>
                        <td><?= $fornecedor['bairro']; ?></td>
                        <td><?= $fornecedor['cidade']; ?></td>
                        <td><?= $fornecedor['contato']; ?></td>
                        <td><?= $fornecedor['email']; ?></td>
                        <td class="text-center"><a class='btn btn-info btn-xs' href="<?php echo $this->url(array('controller' => 'produtocompra', 'action' => 'buscarprodutosporcategoria', 'fornecedorid' => $fornecedor['id'])); ?>"><span class="glyphicon glyphicon-edit"></span>Selecionar</a>
                        </td>

                    </tr>     
                <?php
                }
            }
            ?>
        </table>
    </div>
</div>

