<div class="panel "> <div class="panel-heading panel-primary">
        <div id="actions">
            <a href="<?php echo $this->url(array('controller' => 'produtocompra', 'action' => 'atualizarprodutosecompra')); ?>" class="btn btn-primary btn-xs pull left"><b>+</b>Novo perfil</a>
        </div>                
        <center><h3 class="panel-title">>> Lista de fornecedores cadastrados <<</h3></center>
    </div>
    <div class="panel-body">
        <table class="table table-striped table-hover"> 
            <thead>
                <tr>
                    <th>Razão social</th>
                    <th>Telefone1</th>
                    <th>Telefone2</th>
                    <th>Contato na empresa</th>
                    <th>Email</th>
                    <th class="text-center">Ação</th>
                </tr>
            </thead>
            <tr>
                <?php foreach ($this->listaDeFornecedores as $fornecedor) { ?>
                    <td><?= $fornecedor['razao_social']; ?></td>
                    <td><?= $fornecedor['telefone1']; ?></td>
                    <td><?= $fornecedor['telefone2']; ?></td>
                    <td><?= $fornecedor['contato']; ?></td>
                    <td><?= $fornecedor['email']; ?></td>
                    <td class="text-center"><a class='btn btn-info btn-xs' href="<?php echo $this->url(array('controller' => 'produtocompra', 'action' => 'buscarprodutosporcategoria', 'fornecedorid' => $fornecedor['id'])); ?>"><span class="glyphicon glyphicon-edit"></span>Selecionar</a>
                    </td>
                </tr>     
            <?php } ?>      
        </table>
    </div>
</div>