<center>
    <h1 class="print">Prefeitura do Estado do Rio de Janeiro</h1>
    <h2 class="print">Escola Municipal Mozart Lagos</h2>
    <h3>Relatório de compras por período</h3>
</center>
<hr>
<?php if ($this->compras <> null) { ?>
    <p> Abaixo segue o resultado de sua busca. </p>
<?php } else { ?>
    <p> Não existe compras no período escolhido, porisso seu relatório encontra-se vazio.</p>
<?php } ?>
<center>
    <div class="no-print">
        <form class="form-horizontal" action="<?= $this->baseUrl() . '/relatorio/comprasporperiodo' ?>" method="POST">
            <input type="date" name="data1" class="data" placeholder="Data inicial">
            <input type="date" name="data2" class="data" placeholder="Data fim">
          
            <button class="btn btn-primary btn-sm "><span class="glyphicon glyphicon-search"></span> Pesquisar</button>
        </form>
    </div>
</center>

<div class="row">
    <div class="panel panel-primary filterable">
        <div class="panel-heading">
            <div class="pull-right">
                <button class="btn btn-default btn-xs btn-filter no-print"><span class="glyphicon glyphicon-filter"></span> Buscar na lista</button>
                <button class="btn btn-default btn-xs btn-primary imprimir no-print"><span class="glyphicon glyphicon-print"></span> Imprimir</button>
            </div>
            <span class="glyphicon glyphicon-list"></span> Compras por período
        </div>
        <table class="table table-striped table-hover ">
            <tr>
                <?php if ($this->compras == null) { ?>
                <center><strong><h4>sem resultado para consulta</h4></strong></center>
                </tr>
            <?php } else { ?>
                <thead>
                    <tr class="filters">
                    <tr class="filters">
                        <th><input type="text" class="form-control" placeholder="Código" disabled></th>
                        <th><input type="text" class="form-control" placeholder="Data do pedido" disabled></th>
                        <th><input type="text" class="form-control" placeholder="Data de conclusão" disabled></th>
                        <th><input type="text" class="form-control" placeholder="Status" disabled></th>
                        <th><input type="text" class="form-control" placeholder="Valor da compra" disabled></th>
                    </tr>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <?php foreach ($this->compras as $compra) { ?>
                            <td class="text-left"><?= $compra['id']; ?></td>
                            <td class="text-left"><?= $compra['data_pedido']; ?></td>
                            <?php if ($compra['data_conclusao'] == null) { ?> <td class="text-left"><?= 'não concluída';
                } else {
                                ?></td>
                                <td class="text-left"><?= $compra['data_conclusao']; ?></td>
        <?php } ?>
                            <td class="text-left"><?= $compra['status']; ?></td>
                            <td class="text-left"><?= $compra['valor_total']; ?></td>
                        </tr> 
                        <?php
                    }
                }
                ?>
                </tr>
            </tbody>
        </table>
    </div>     
</div>


