<center>
<h1 class="print">Prefeitura do Estado do Rio de Janeiro</h1>
<h2 class="print">Escola Municipal Mozart Lagos</h2>
<h3>Relatório de produtos mais solicitados</h3>
</center>
<hr>
<center>
<div class="no-print">
    <form class="form-horizontal" action="<?= $this->baseUrl() . '/relatorio/produtosmaissolicitados' ?>" method="POST">
        <input type="date" name="data1" class="data" placeholder="Data inicial">
<!--        <span class="help-block"></span>-->
        <input type="date" name="data2" class="data" placeholder="Data fim">
        <button class="btn btn-primary btn-sm "><span class="glyphicon glyphicon-search"></span> Pesquisar</button>
    </form>
</div>
</center>
<div class="row">
    <div class="panel panel-primary filterable">
        <div class="panel-heading">
             <div class="pull-right">
                    <button class="btn btn-default btn-xs btn-filter no-print"><span class="glyphicon glyphicon-filter"></span> Buscar na lista</button>
                    <button class="btn btn-default btn-xs btn-primary imprimir no-print"><span class="glyphicon glyphicon-print"></span> Imprimir</button>
                </div>
            <span class="glyphicon glyphicon-list"></span> Produtos mais solicitados
        </div>
        <table class="table table-striped table-hover ">
            <tr>
                <?php if ($this->solicitacoes == null) { ?>
                <center><strong><h4>sem resultado para consulta</h4></strong></center>
                </tr>
            <?php } else { ?>
                <thead>
                    <tr class="filters">
                    <tr class="filters">
                        <th><input type="text" class="form-control" placeholder="Produto" disabled></th>
                        <th><input type="text" class="form-control" placeholder="Quantidade total" disabled></th>
                    </tr>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <?php foreach ($this->produtos as $produto) { ?>
                            <td class="text-left"><?= $produto['nome']; ?></td>
                            <td class="text-left"><?= $produto['total']; ?></td>
                        </tr> 
                        <?php
                    }
                }
                ?>
                </tr>
            </tbody>
        </table>
    </div>     
</div>


