<?php 
$usuario = Zend_Auth::getInstance()->getIdentity()->login;
?>


<center>
    <h1 class="print">Prefeitura do Estado do Rio de Janeiro</h1>
    <h2 class="print">Centro Integrado de Educação Pública (CIEP) Almir Bonfim de Andrade </h2>
    <h3>Relatório de solicitações por período</h3>
</center>
<div class="pull-right">Impresso em: <?php echo $data = date("d/m/Y - H:i:s ") . 'por ' . '<b>'.$usuario.'</b>'; ?></div>
<hr>
<?php if ($this->solicitacoes <> null) { ?>
    <p> Abaixo segue o resultado de sua busca. </p>
<?php } else { ?>
    <p> Não existe solicitações no período escolhido, porisso seu relatório encontra-se vazio.</p>
<?php } ?>
<center>
    <div class="no-print">
        <form class="form-horizontal" action="<?= $this->baseUrl() . '/relatorio/solicitacoesporperiodo' ?>" method="POST">
            <input type="date" required="true" name="data1" class="data" placeholder="Data inicial">
    <!--        <span class="help-block"></span>-->
            <input type="date" required="true" name="data2" class="data" placeholder="Data fim">
            <br>
            <br>
                <select  name="status">
                    <option value="">--selecione--</option>
                    <option value="nova">Nova</option>
                    <option value="em analise">Em análise</option>
                    <option value="aprovada">Aprovada</option>
                    <option value="reprovada">Reprovada</option>
                    <option value="cancelada">Cancelada</option>
                    <option value="entregue">Entregue</option>
                    <option value="recebida">Recebida</option>
                    <option value="agendada">Agendada</option>
                    <option value="pendente">Pendente</option>
                    <option value="liberada">Liberada</option>

                </select>
            <button class="btn btn-primary btn-sm "><span class="glyphicon glyphicon-search"></span> Pesquisar</button>
            <small><span class="help-block">* Se nenhum status for selecionado, a consulta irá retornar todos os status</span></small>
        </form>
    </div>
</center>

<div class="row">
    <div class="panel panel-primary filterable">
        <div class="panel-heading">
            <div class="pull-right">
                <button class="btn btn-default btn-xs btn-filter no-print"><span class="glyphicon glyphicon-filter"></span> Buscar na lista</button>
                <button class="btn btn-default btn-xs btn-primary imprimir no-print"><span class="glyphicon glyphicon-print"></span> Imprimir</button>
            </div>
            <span class="glyphicon glyphicon-list"></span> Solicitações por período
        </div>
        <table class="table table-striped table-hover ">
            <tr>
                <?php if ($this->solicitacoes == null) { ?>
                <center><strong><h4>sem resultado para consulta</h4></strong></center>
                </tr>
            <?php } else { ?>
                <thead>
                    <tr class="filters">
                    <tr class="filters">
                        <th><input type="text" class="form-control" placeholder="Código" disabled></th>
                        <th><input type="text" class="form-control" placeholder="Data de criação" disabled></th>
                        <th><input type="text" class="form-control" placeholder="Data de recebimento" disabled></th>
                        <th><input type="text" class="form-control" placeholder="Status" disabled></th>
                        <th><input type="text" class="form-control" placeholder="Usuário" disabled></th>
                    </tr>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <?php foreach ($this->solicitacoes as $solicitacao) {?>
                        
                            <td class="text-left"><?= $solicitacao['id']; ?></td>
                            <td class="text-left"><?= $solicitacao['data']; ?></td>
                            <?php if ($solicitacao['data_recebimento'] == null) { ?> <td class="text-left"><?=
                                'não possui';
                            } else {
                                ?></td>
                                <td class="text-left"><?= $solicitacao['data_recebimento']; ?></td>
                            <?php } ?>
                            <td class="text-left"><?= $solicitacao['status']; ?></td>
                            <td class="text-left"><?= $solicitacao['login']; ?></td>
                        </tr> 
                        <?php
                    }
                }
                ?>
                </tr>
            </tbody>
        </table>
    </div>     
</div>


