<?php
$usuario = Zend_Auth::getInstance()->getIdentity()->login;
?>
<center>
    <h1 class="print">Prefeitura do Estado do Rio de Janeiro</h1>
    <h2 class="print">Centro Integrado de Educação Pública (CIEP) Almir Bonfim de Andrade </h2>
    <h3>Relatório de usuários por perfil</h3>
</center>
<p> Abaixo segue o resultado de sua busca. </p>
<hr>
<div class="panel panel-primary filterable">
    <div class="panel-heading">
        <div class="pull-right">
            <button class="btn btn-default btn-xs btn-filter no-print"><span class="glyphicon glyphicon-filter"></span> Buscar na lista</button>
            <button class="btn btn-default btn-xs btn-primary imprimir no-print"><span class="glyphicon glyphicon-print"></span> Imprimir</button>
        </div>
        <span class="glyphicon glyphicon-list"></span> Solicitações por usuário: <b><?= $this->login; ?></b> 
    </div>
    <table class="table table-striped table-hover tabela-busca">
        <thead>
            <tr class="filters">
                <th><input type="text" class="form-control" placeholder="Código" disabled></th>
                <th><input type="text" class="form-control" placeholder="Data de criação" disabled></th>
                <th><input type="text" class="form-control" placeholder="Data de recebimento" disabled></th>
                <th><input type="text" class="form-control" placeholder="Status" disabled></th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <?php foreach ($this->solicitacoes as $solicitacao) { ?>
                    <td class="text-left"><?= $solicitacao['id']; ?></td>
                    <td class="text-left"><?= $solicitacao['data']; ?></td>
                    <?php if ($solicitacao['data_recebimento'] == null) { ?> <td class="text-left"><?= 'não concluída';
            } else {
                        ?></td>
                        <td class="text-left"><?= $solicitacao['data_recebimento']; ?></td>
    <?php } ?>
                    <td class="text-left"><?= $solicitacao['status']; ?></td>
                </tr> 
                <?php
            }
            ?>
            </tr>
        </tbody>
    </table>
</div>     



