<h3>Lista de compras ativas</h3>
<hr>
<?php if ($this->listaDeCompras->current() <> null) { ?>
    <p> Abaixo seguem suas compras ativas, para criar seu carrinho de compras, selecione <b>abaixo</b> o botão <a class='btn btn-success btn-xs disabled'><span class="glyphicon glyphicon-usd"></span> Iniciar</a> para selecionar seu fornecedor</p>
<?php } else { ?>
    <p> Você não tem ainda compras ativas, mas você pode criar a sua agora mesmo, <a href="<?php echo $this->url(array('controller' => 'compra', 'action' => 'inserir')); ?>">Clique aqui</a> </p>
<?php } ?>

<div class="row">
    <div class="panel panel-primary filterable">
        <div class="panel-heading">
            <span class="glyphicon glyphicon-list"></span>Lista de compras ativas
        </div>
        <table class="table table-striped table-hover ">
            <tr>
                <?php if ($this->listaDeCompras->current() == null) { ?>
                <center><strong><h4>sem compras criadas</h4></strong></center>
                </tr>
            <?php } else { ?>
                <thead>
                    <tr class="filters text-center">
                        <th class="text-center">Código</th>
                        <th class="text-center">Status</th>
                        <th class="text-center">Data do pedido</th>
                        <th class="text-center">Ação</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <?php foreach ($this->listaDeCompras as $compra) { ?>

                            <td><?= $compra['id']; ?></td>
                            <td><?= $compra['status']; ?></td>
                            <?php if ($compra['data_pedido'] == null) { ?>
                                <td><?= 'não iniciada' ?> </td>
                            <?php } else { ?>
                                <td><?= $compra['data_pedido']; ?></td>
                            <?php } ?>
                            <td class="text-center acao">
                                <?php if ($compra['status'] == 'nova') { ?>
                                    <a class='btn btn-success btn-xs' href="<?php echo $this->url(array('controller' => 'produtocompra', 'action' => 'listarfornecedores', 'compraid' => $compra['id'])); ?>"><span class="glyphicon glyphicon-usd"></span> Iniciar</a>                                    
                                    <a href="<?php echo $this->url(array('controller' => 'compra', 'action' => 'deletar', 'id' => $compra['id'])); ?>" class="btn btn-danger btn-xs"><span class="glyphicon glyphicon-remove"></span> Excluir</a>
                                <?php } elseif ($compra['status'] == 'AGUARDANDO FORNECEDOR') { ?>
                                    <a href="<?php echo $this->url(array('controller' => 'compra', 'action' => 'deletar', 'id' => $compra['id'])); ?>" class="btn btn-danger btn-xs"><span class="glyphicon glyphicon-remove"></span> Cancelar</a>
                                    <a href="<?php echo $this->url(array('controller' => 'produtocompra', 'action' => 'resumodepedido', 'compraid' => $compra['id'])); ?>" class="btn btn-default btn-xs"><span class="glyphicon glyphicon-eye-open"></span> Visualizar</a>
                                <?php } ?>
                            </td>
                        </tr>
                    <?php } ?>
                </tbody>
            <?php } ?>
    </div>
</div>
