<?php echo $this->doctype(); ?>
<html>
    <head>
        <?php echo $this->headMeta(); ?>
        <?php echo $this->headTitle(); ?>
        <?php
        echo $this->headLink()->prependStylesheet($this->baseUrl() . '/styles/style.css')
                ->prependStylesheet($this->baseUrl() . '/styles/bootstrap.min.css');
        ?>

        <?php
        echo $this->headScript()->appendFile($this->baseUrl() . '/js/javascript.js')
                ->prependFile($this->baseUrl() . '/js/bootstrap.min.js')
            ->prependFile($this->baseUrl() . '/js/jquery/jquery.maskMoney.min.js')
            ->prependFile($this->baseUrl() . '/js/jquery/jquery-2.1.1.js');

        ?>

    </head>

    <body>
        <?php echo $this->partial("navbar.phtml"); ?>
        <?php echo $this->partial("header.phtml"); ?>
        <div class="container">
            <div class="row">
                <?php $perfil = Zend_Auth::getInstance()->getIdentity()->perfilid; ?>
                <?php
                if ($perfil == 2 || $perfil == 3) {
                    echo $this->partial("controle.phtml");
                } else {
                    ?>
                    <div class="somecontrole" style= "display: none">
                        <?php echo $this->partial("controle.phtml"); ?>
                    </div>
                <?php } ?>


                <?php $mensagens = isset($this->layout()->flashMessenger) ? $this->layout()->flashMessenger->getMessages() : array() ?>
                <?php foreach ($mensagens as $key => $mensagem): ?>

                    <div class="alert alert-<?= key($mensagem) ?> ">
                        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                        <p class="alerta"><?= $mensagem[key($mensagem)] ?></p>
                    </div>

                <?php endforeach ?>

                <?= $this->layout()->content; ?>
            </div>
        </div>
    </body>
</html>
