<div class="navbar navbar-default no-print">
    <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="<?php echo $this->url(array('controller' => 'solicitacao', 'action' => 'listar')); ?>" ><i class="glyphicon glyphicon-home"></i> Início</a>
    </div>
    <div class="navbar-collapse collapse navbar-responsive-collapse">
        <ul class="nav navbar-nav">
            <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="glyphicon glyphicon-th-large"></i> Produto <b class="caret"></b></a>
                <ul class="dropdown-menu">
                    <li class="dropdown-header">Consultar produtos</li>
                    <li>
                        <a href="<?php echo $this->url(array('controller' => 'categoria', 'action' => 'selecionarcategoria', 'listaDeProdutos' => true)); ?>">Consultar por categoria</a>
                    </li>
                </ul>
            </li>
            <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="glyphicon glyphicon-list"></i> Minha Solicitação <b class="caret"></b></a>
                <ul class="dropdown-menu">
                    <li>
                        <a href="<?php echo $this->url(array('controller' => 'solicitacao', 'action' => 'inserir')); ?>"><i class="Solicitaçãoglyphicon glyphicon-plus"></i> Fazer nova</a>
                    </li>
                    <li class="dropdown-header">Solicitações em andamento</li>
                    <li>
                    <li><a href="<?php echo $this->url(array('controller' => 'solicitacao', 'action' => 'listaragendadas')); ?>"> Minhas agendadas</a></li>
            </li>
            <li>
                <a href="<?php echo $this->url(array('controller' => 'solicitacao', 'action' => 'listarreprovadas')); ?>">Minhas reprovadas</a>
            </li>  
            <li class="dropdown-header">Devolução</li>
            <li>
                <a href="<?php echo $this->url(array('controller' => 'devolucao', 'action' => 'listardevolucao')); ?>" > Devoluções ativas</a>
            </li>
            <li class="dropdown-header">Histórico</li>
            <li>
                <a href="<?php echo $this->url(array('controller' => 'solicitacao', 'action' => 'listarhistorico')); ?>" > Solicitações e agendamentos</a>
                <a href="<?php echo $this->url(array('controller' => 'devolucao', 'action' => 'listardevolucaoantiga')); ?>" > Devoluções antigas</a>
            </li>

            <li class="divider"></li>
        </ul>                
        </li>
        </ul>
        <form class="navbar-form navbar-left" action="<?= $this->baseUrl() . '/solicitacao/buscarsolicitacao' ?>" method="POST">
            <input class="form-control col-lg-8" placeholder="Nº da solicitação" type="text" name="solicitacaoid">
        </form>
        <ul class="nav navbar-nav navbar-right">    
            <li class="dropdown">
                <a href ="" class="dropdown-toggle" data-toggle="dropdown"><i class="glyphicon glyphicon-cog"></i> <b class="caret"></b></a>
                <ul class="dropdown-menu">
                    <li>
                        <a href="<?php echo $this->url(array('controller' => 'usuario', 'action' => 'perfilusuario')); ?>"><i class="glyphicon glyphicon-user"></i> Perfil</a>
                    </li>
                    <li class="divider"></li>
                    <li>
                        <a href="<?php echo $this->url(array('controller' => 'auth', 'action' => 'logout')); ?>"><i class="glyphicon glyphicon-off"></i> Sair</a>
                    </li>
                </ul>
            </li>
        </ul>
    </div>
</div>
