<form class="form-horizontal" action="<?= $this->baseUrl() . '/pessoa/editar' ?>" method="POST">
    <fieldset>
        <legend>Editar funcionário</legend>
        <input type="hidden" name="id" value="<?php echo $this->pessoa->id ?>">
        <div class="form-group">
            <label for="inputMatricula" class="col-lg-2 control-label">Matricula</label>
            <div class="col-lg-2">
                <input class="form-control" id="inputMatricula" placeholder="Ex: 6207669" type="text" name="matricula" required="required" pattern="[0-9]+$" value="<?php echo $this->pessoa->matricula?>">
                <span class="help-block">Apenas números.</span>
            </div>
        </div>
        <div class="form-group">
            <label for="inputNome" class="col-lg-2 control-label">Nome</label>
            <div class="col-lg-6">
                <input class="form-control" id="inputNome" placeholder="Nome completo" type="text" name="nome" required="true" value="<?php echo $this->pessoa->nome?>">
            </div>
        </div>
        <div class="form-group">
            <label for="select" class="col-lg-2 control-label">Função</label>
            <div class="col-lg-2">
                <select required="true" class="form-control" id="select" name="funcaoid" required="true">
                    <option value="">--selecione--</option>
                    <?php foreach ($this->funcoes as $nomeFuncao):?> 
                        <option value="<?php echo $nomeFuncao['id']; ?>"><?php echo $nomeFuncao['nome']; ?></option> 
                        <?php
                    endforeach;
                    ?> 
                </select>     
                <br>
            </div>
        </div>
        <div class="form-group">
            <label for="inputTelefone1" class="col-lg-2 control-label">Telefone Principal</label>
            <div class="col-lg-2">
                <input class="form-control" type="tel" required="required" maxlength="15" name="telefone1" placeholder="ex: 98556452" value="<?php echo $this->pessoa->telefone1?>"/>
            </div>
        </div>
        <div class="form-group">
            <label for="inputTelefone2" class="col-lg-2 control-label">Outro telefone</label>
            <div class="col-lg-2">
                <input class="form-control" type="tel" required="required" maxlength="15" name="telefone2" placeholder="ex: 2124647256" value="<?php echo $this->pessoa->telefone2?>"/>
            </div>
        </div>
        <div class="form-group">
            <div class="col-lg-10 col-lg-offset-2">
                <a class="btn btn-primary" href="<?php echo $this->url(array('controller' => 'pessoa', 'action' => 'listar')); ?>">Voltar</a>
                <button type="submit" class="btn btn-success">Editar</button>
            </div>
        </div>
    </fieldset>
</form>

