<div class="panel "> <div class="panel-heading panel-primary">
        <div id="actions">
            <a href="<?php echo $this->url(array('controller' => 'pessoa', 'action' => 'inserir')); ?>" class="btn btn-primary btn-xs pull left"><b>+</b>Novo funcionário</a>            
        </div>                
        <center><h3 class="panel-title">>> Lista de funcionários cadastrados <<</h3></center>
    </div>
    <div class="panel-body">
        <table class="table table-striped table-hover"> 
            <thead>             
                <tr>
                    <th>ID</th>
                    <th>Matricula</th>
                    <th>Nome</th>
                    <th>Função</th>
                    <th>Telefone1</th>
                    <th>Telefone2</th>                
                    <th class="text-center">Ação</th>
                </tr>
            </thead>
            <tr>
                <?php foreach ($this->listaDePessoas as $pessoa) { ?>
                    <?php
                    $tFuncao = new Funcao();
                    $funcaoNome = $tFuncao->findFuncaoById($pessoa['funcaoid']);
                    ?>
                    <td><?= $pessoa['id']; ?></td>
                    <td><?= $pessoa['matricula']; ?></td>
                    <td><?= $pessoa['nome']; ?></td>
                    <td><?= $funcaoNome['funcaoid']->nome;
                ;
                    ?></td>
                    <td><?= $pessoa['telefone1']; ?></td>
                    <td><?= $pessoa['telefone2']; ?></td>
                    <td class="text-center"><a class='btn btn-info btn-xs' href="<?php echo $this->url(array('controller' => 'pessoa', 'action' => 'editar', 'id' => $pessoa['id'])); ?>"><span class="glyphicon glyphicon-edit"></span>Editar</a> <a href="<?php echo $this->url(array('controller' => 'pessoa', 'action' => 'deletar', 'id' => $pessoa['id'])); ?>" class="btn btn-danger btn-xs"><span class="glyphicon glyphicon-remove"></span>Deletar</a></td>
                </tr>     
<?php } ?>      
        </table>
    </div>
</div>
