<legend>Funcionários cadastrados</legend>
<hr>
<div class="panel panel-primary"> 
   <div class="panel-heading" id="actions"><span class="glyphicon glyphicon-list"></span> Lista de funcionários cadastrados
      <a href="<?php echo $this->url(array('controller' => 'pessoa', 'action' => 'inserir')); ?>" class="btn btn-info btn-xs pull-right" style="border:2"><span class="glyphicon glyphicon-plus"></span>Novo funcionário</a>
   </div>
    <div class="panel-body">
        <table class="table table-striped table-hover"> 
            <thead>             
                <tr>
                    <th>ID</th>
                    <th>Matrícula</th>
                    <th>Nome</th>
                    <th>Função</th>
                    <th>Telefone principal</th>
                    <th>Outro telefone</th>                
                    <th></th>
                    <th></th>
                </tr>
            </thead>
            <tr>
                <?php foreach ($this->listaDePessoas as $pessoa) { ?>
                    <?php
                    $tFuncao = new Funcao();
                    $funcaoNome = $tFuncao->findFuncaoById($pessoa['funcaoid']);
                    ?>
                    <td><?= $pessoa['id']; ?></td>
                    <td><?= $pessoa['matricula']; ?></td>
                    <td><?= $pessoa['nome']; ?></td>
                    <td><?= $funcaoNome['funcaoid']->nome;?></td>
                    <td><?= $pessoa['telefone1']; ?></td>
                    <td><?= $pessoa['telefone2']; ?></td>
                    <td class="text-center"><a class='btn btn-warning btn-block btn-xs' href="<?php echo $this->url(array('controller' => 'pessoa', 'action' => 'editar', 'id' => $pessoa['id'])); ?>"><span class="glyphicon glyphicon-edit"></span>Editar</a></td> 
                    <td class="text-center"><a href="<?php echo $this->url(array('controller' => 'pessoa', 'action' => 'deletar', 'id' => $pessoa['id'])); ?>" class="btn btn-danger btn-block btn-xs"><span class="glyphicon glyphicon-remove-circle"></span>Excluir</a></td>
                </tr>     
<?php } ?>      
        </table>
    </div>
</div>
