<form class="form-horizontal" action="<?= $this->baseUrl() . '/categoria/editar' ?>" method="POST">
 <input type="hidden" name="id" value="<?php echo $this->categoria->id ?>">
    <fieldset>
        <legend>Cadastrar categoria</legend>
        <div class="form-group">
            <label for="inputNome" class="col-lg-4 control-label" required="true">Nome</label>
            <div class="col-lg-6">
                <input class="form-control" id="inputNome" placeholder="" type="text" name="nome" value="<?php echo $this->categoria->nome ?>">
            </div>
        </div>    
        <div class="form-group">
            <label for="Descrição" class="col-lg-4 control-label">Descrição</label>
            <div class="col-lg-6">
                <textarea class="form-control" rows="3" id="descricao" name="descricao" required="true"><?php echo $this->categoria->descricao ?></textarea>
                <span class="help-block">Faça uma breve descrição a categoria a ser cadastrada</span>
            </div>
        </div>    
        <div class="form-group">
            <div class="col-lg-6 col-lg-offset-6">
                <a class="btn btn-primary" href="<?php echo $this->url(array('controller' => 'categoria', 'action' => 'listar')); ?>">Voltar</a>
                <button type="submit" class="btn btn-success">Editar</button>
            </div>
        </div>
    </fieldset>
</form>