<form class="form-horizontal" action="<?= $this->baseUrl() . '/categoria/inserir' ?>" method="POST">
    <fieldset>
        <legend>Criando novo perfil</legend>
        <div class="form-group">
            <label for="inputNome" class="col-lg-2 control-label">Nome</label>
            <div class="col-lg-10">
                <input class="form-control" id="inputNome" placeholder="" type="text" name="nome">
            </div>
        </div>    
        <div class="form-group">
            <label for="Descrição" class="col-lg-2 control-label">Descrição</label>
            <div class="col-lg-10">
                <textarea class="form-control" rows="3" id="descricao" name="descricao"></textarea>
                <span class="help-block">Faça uma breve descrição sobre o perfil a ser criado</span>
            </div>
        </div>
        <div class="form-group">
            <label for="inputTrigrama" class="col-lg-2 control-label">Trigrama</label>
            <div class="col-lg-10">
                <input class="form-control" id="inpuTrigrama" placeholder="" type="text" name="trigrama">
                <span class="help-block">Idenfifique a categoria com 3 letras</span>
            </div>
        </div>
        <div class="form-group">
            <div class="col-lg-10 col-lg-offset-2">
                <button type="submit" class="btn btn-primary">Inserir</button>                
            </div>
        </div>
    </fieldset>
</form>
<a href="<?php echo $this->url(array('controller' => 'categoria', 'action' => 'listar')); ?>"><button class="btn btn-default">Cancelar</button></a>
