<legend>Categorias cadastrados</legend>
<hr>
<?php if ($this->listaDeCategorias <> null) { ?>
    <p> Abaixo seguem suas categorias cadastradas </p>
<?php } else { ?>
    <p> Você não tem ainda categorias cadastradas</p>
<?php } ?>

<div class="panel panel-primary"> 
    <div class="panel-heading" id="actions"><span class="glyphicon glyphicon-list"></span> Lista de categorias cadastrados
        <a href="<?php echo $this->url(array('controller' => 'categoria', 'action' => 'inserir')); ?>" class="btn btn-info btn-xs pull-right" style="border:2"><span class="glyphicon glyphicon-plus"></span>Nova categoria</a>
    </div>
    <div class="panel-body">
        <table class="table table-striped table-hover"> 
            <tr>
                <?php if ($this->listaDeCategorias == null) { ?>
                <center><strong><h4>sem categoria cadastrada</h4></strong></center>
                </tr>
            <?php } else { ?>
                <thead>             
                    <tr>
                        <th>Nome</th>
                        <th>Descrição</th>
                    </tr>
                </thead>
                <?php foreach ($this->listaDeCategorias as $categoria) { ?>
                    <tr>
                        <td><?= $categoria['nome']; ?></td>
                        <td><?= $categoria['descricao']; ?></td>
                        <td><a class='btn btn-warning btn-block btn-xs' href="<?php echo $this->url(array('controller' => 'categoria', 'action' => 'editar', 'id' => $categoria['id'])); ?>"><span class="glyphicon glyphicon-edit"></span> Editar</a></td>
                        <td><a href="<?php echo $this->url(array('controller' => 'categoria', 'action' => 'deletar', 'id' => $categoria['id'])); ?>" class="btn btn-danger btn-block btn-xs"><span class="glyphicon glyphicon-remove-circle"></span> Excluir</a></td>

                    </tr>     
                    <?php
                }
            }
            ?>      
        </table>
    </div>
</div>
