<div class="panel "> <div class="panel-heading panel-primary">
        <div id="actions">
            <a href="<?php echo $this->url(array('controller' => 'categoria', 'action' => 'inserir')); ?>" class="btn btn-primary btn-xs pull left"><b>+</b>Nova categoria</a>
        </div> 
        <center><h3 class="panel-title">>> Lista de categorias cadastradas <<</h3></center>
    </div>
    <div class="panel-body">
        <table class="table table-striped table-hover">        
            <thead>            
            <tr>
                <th>ID</th>
                <th>Nome</th>
                <th>Descrição</th>
                <th>Trigrama</th>
                <th class="text-center">Ação</th>
            </tr>
            </thead>
            <tr>
                <?php foreach ($this->listaDeCategorias as $categoria) { ?>
                    <td><?= $categoria['id']; ?></td>
                    <td><?= $categoria['nome']; ?></td>
                    <td><?= $categoria['descricao']; ?></td>
                    <td><?= $categoria['trigrama']; ?></td>
                    <td class="text-center"><a class='btn btn-info btn-xs' href="<?php echo $this->url(array('controller' => 'categoria', 'action' => 'editar', 'id' => $categoria['id'])); ?>"><span class="glyphicon glyphicon-edit"></span>Editar</a>
                        <a href="<?php echo $this->url(array('controller' => 'categoria', 'action' => 'deletar', 'id' => $categoria['id'])); ?>" class="btn btn-danger btn-xs"><span class="glyphicon glyphicon-remove"></span>Deletar</a>
                    </td>
                </tr>     
            <?php } ?>      
        </table>
    </div>
</div>
