<h3>Pesquisar produto por categoria</h3>
<hr>
<div class="instrucao">
    <p>Escolha uma das categorias cadastradas abaixo para listar seus produtos:</p>
    
    <div class="combobox">
        <form class="form-horizontal" action="<?= $this->baseUrl() . '/produto/buscarprodutoporcategoria' ?>" method="POST">
            <select name="categoriaid">
                <option></option>
                <?php foreach ($this->listadecategorias as $nomeCategoria): ?>
                    <option value="<?php echo $nomeCategoria['id']; ?>"><?php echo $nomeCategoria['nome']; ?></option>
                    <?php
                endforeach;
                ?>
            </select>
             <button class="btn btn-info btn-filter btn-sm"><span class="glyphicon glyphicon-search"></span> Pesquisar</button>
        </form>
    </div>
        
</div>
