<h3>Lista de Produtos</h3>
<hr>
<div class="instrucao">
    <p>Busque a categoria desejada e visualize os produtos cadastrados</p>
    
    <div class="combobox">
        <form class="form-horizontal" action="<?= $this->baseUrl() . '/produto/buscarprodutoporcategoria' ?>" method="POST">
            <select name="categoriaid">
                <option></option>
                <?php foreach ($this->listadecategorias as $nomeCategoria): ?>
                    <option value="<?php echo $nomeCategoria['id']; ?>"><?php echo $nomeCategoria['nome']; ?></option>
                    <?php
                endforeach;
                ?>
            </select>
            <button class="btn btn-default btn-xs btn-filter" ><span class="glyphicon glyphicon-search"></span> Buscar</button>
        </form>
    </div>
        
</div>
