<h3>Inserir observação</h3>
<hr>
<div class="instrucao">
    <form class="form-horizontal" action="" method="POST">
        <input type ="hidden" name="solicitacaoid" value ="<?= $this->solicitacaoid; ?>">
        <input type ="hidden" name="produtosolicitacaoid" value ="<?= $this->produtosolicitacaoid; ?>">
        <input type ="hidden" name="solicitacaoid" value ="<?= $this->solicitacaoid; ?>">
        <br><br>
        <div class="form-group">
            <div class="col-lg-3  col-lg-offset-4">
                <textarea class="form-control" rows="3" id="observacao" required="true" name="observacao"></textarea>
                <span class="help-block">Insira um comentário sobre esta ação</span>
            </div>
        </div>       
        <div class="form-group">
            <div class="col-lg-4 col-lg-offset-4">
                <button type="submit" class="btn btn-success btn-block"><span class="glyphicon glyphicon-ok"></span> Inserir observação</button>
            </div>
        </div>
    </form>

</div>
