<h3>Lista de solicitações para análise</h3>
<hr>
<?php if ($this->listaDeSolicitacoes->current() <> null) { ?>
    <p> Abaixo segue uma lista de solicitação para serem analisadas. Visualize o que está sendo solicitado em 'Visualizar' e escolha uma ação.
<?php } else { ?>
    <p> Não existem solicitações para ser analisada na base de dados.</p> 
<?php } ?>

<div class="panel panel-primary filterable conteudogerente">
    <div class="panel-heading">
        <span class="glyphicon glyphicon-list"></span>Lista de Solicitações
    </div>
    <table class="table">
        <tr>
            <?php if ($this->listaDeSolicitacoes->current() == null) { ?>
            <center><strong><h4>sem solicitações</h4></strong></center>
            </tr>
        <?php } else { ?>
            <thead>
                <tr class="filters">
                    <th><input type="text" class="form-control" placeholder="Código" disabled></th>
                    <th><input type="text" class="form-control" placeholder="Data" disabled></th>
                    <th><input type="text" class="form-control" placeholder="Status" disabled></th>  
                    <th class="text-center">Ação</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <?php foreach ($this->listaDeSolicitacoes as $solicitacao) { ?>
                        <td><?= $solicitacao['id']; ?></td>
                        <td><?= $solicitacao['data']; ?></td>
                        <td><?= $solicitacao['status']; ?></td>
                        <td class="text-center">
                            <a href="<?php echo $this->url(array('controller' => 'produtosolicitacao', 'action' => 'atualizarprodutosesolicitacao', 'solicitacaoid' => $solicitacao['id'], 'status' => 'aprovada', 'data_envio' => $data_envio = date("m-d-Y"))); ?>" class="btn btn-default btn-xs"><span class="glyphicon glyphicon-ok"></span>Aprovar</a>
                            <a href="<?php echo $this->url(array('controller' => 'produtosolicitacao', 'action' => 'atualizarprodutosesolicitacao', 'solicitacaoid' => $solicitacao['id'], 'status' => 'reprovada')); ?>" class="btn btn-default btn-xs"><span class="glyphicon glyphicon-ok"></span>Reprovar</a>
                        </td>
                    </tr> 
                <?php
                }
            }
            ?>
            </tr>
        </tbody>
    </table>
</div>     



