<h3>Lista de solicitações agendadas</h3>
<hr>
<?php if ($this->agendadas->current() <> null) { ?>
    <p> Abaixo seguem suas solicitações agendadas. </p>
<?php } else { ?>
    <p> Não consta nenhma solicitação agendada até o momento na base de dados.</a> </p>
<?php } ?>

<div class="row">
    <div class="panel panel-primary filterable">
        <div class="panel-heading">
            <span class="glyphicon glyphicon-list"></span> Solicitações agendadas
        </div>
        <table class="table table-striped table-hover ">
            <tr>
                <?php if ($this->agendadas->current() == null) { ?>
                <center><strong><h4>sem solicitações agendadas</h4></strong></center>
                </tr>
            <?php } else { ?>
                <thead>
                    <tr class="filters">
                        <th>Código</th>
                        <th>Status</th>
                        <th>Data de agendamento</th>

                        <th class="text-center">Ação</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <?php foreach ($this->agendadas as $solicitacao) { ?>
                            <td><?= $solicitacao['id']; ?></td>
                            <td><?= $solicitacao['status']; ?></td>
                            <td><?= $solicitacao['data_agendamento']; ?></td>
                            <td class="text-center">   
                                <?php
                                $login = Zend_Auth::getInstance()->getIdentity()->login;
                                $perfil = Zend_Auth::getInstance()->getIdentity()->perfilid;

                                if (($perfil == 2 || $perfil == 3) && ($solicitacao['status'] == 'agendada')) {
                                    ?>

                                    <a href="<?php echo $this->url(array('controller' => 'solicitacao', 'action' => 'inserirobservacao', 'solicitacaoid' => $solicitacao['id'], 'status' => 'pendente', 'data_atualizacao_status' => $data_atualizacao_status = date("m-d-Y"), 'gerente_responsavel' => $login)); ?>" class='btn btn-warning btn-xs'><span class="glyphicon glyphicon-remove-circle"></span> Pendente</a>

                                <?php } elseif (($solicitacao['status'] == 'agendada') || ($solicitacao['status'] == 'pendente')) { ?>

                                    <a href="<?php echo $this->url(array('controller' => 'solicitacao', 'action' => 'cancelarsolicitacao', 'solicitacaoid' => $solicitacao['id'], 'status' => 'cancelada')); ?>" class='btn btn-danger btn-xs'><span class="glyphicon glyphicon-remove-circle"></span> Cancelar</a>               
                                <?php } ?>         
                                <a href="<?php echo $this->url(array('controller' => 'produtosolicitacao', 'action' => 'resumodesolicitacao', 'solicitacaoid' => $solicitacao['id'])); ?>" class='btn btn-default btn-xs'><span class="glyphicon glyphicon-eye-open"></span> Visualizar</a>
                            </td>
                        </tr> 
                        <?php
                    }
                }
                ?>
                </tr>
            </tbody>
        </table>
    </div>     
</div>


