<h3>Lista de solicitações reprovadas</h3>
<hr>
<?php if ($this->reprovadas->current() <> null) { ?>
<p> Abaixo seguem suas solicitações reprovadas. </p>
<?php } else { ?>
    <p> Não consta nenhma solicitação reprovada até o momento na base de dados.</a> </p>
<?php } ?>

<div class="row">
    <div class="panel panel-primary filterable">
        <div class="panel-heading">
            <span class="glyphicon glyphicon-list"></span>Solicitações Reprovadas
        </div>
        <table class="table">
            <tr>
                <?php if ($this->reprovadas->current() == null) { ?>
                <center><strong><h4>sem solicitações reprovadas</h4></strong></center>
                </tr>
            <?php } else { ?>
                <thead>
                    <tr class="filters">
                        <th><input type="text" class="form-control" placeholder="Código" disabled></th>
                        <th><input type="text" class="form-control" placeholder="Data" disabled></th>
                         
                        <th class="text-center">Ação</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <?php foreach ($this->reprovadas as $solicitacao) { ?>
                            <td><?= $solicitacao['id']; ?></td>
                            <td><?= $solicitacao['data_reprovacao']; ?></td>
                            
                            <td class="text-center"><a class='btn btn-info btn-xs' href="<?php echo $this->url(array('controller' => 'produtosolicitacao', 'action' => 'carrinhodesolicitacoes', 'solicitacaoid' => $solicitacao['id'])); ?>"><span class="glyphicon glyphicon-edit"></span>Visualizar</a>

                        </tr> 
                    <?php }
                }
                ?>
                </tr>
            </tbody>
        </table>
    </div>     
</div>


