<h3>Lista de solicitações canceladas</h3>
<hr>
<?php if ($this->canceladas->current() <> null) { ?>
    <p> Abaixo seguem suas solicitações canceladas. </p>
<?php } else { ?>
    <p> Não consta nenhma solicitação cancelada até o momento na base de dados.</a> </p>
<?php } ?>

<div class="row">
    <div class="panel panel-primary filterable">
        <div class="panel-heading">
            <span class="glyphicon glyphicon-list"></span> Solicitações canceladas
        </div>
        <table class="table table-striped table-hover ">
            <tr>
                <?php if ($this->canceladas->current() == null) { ?>
                <center><strong><h4>sem solicitações agendadas</h4></strong></center>
                </tr>
            <?php } else { ?>
                <thead>
                    <tr class="filters">
                        <th>Código</th>
                        <th>Status</th>
                        <th class="text-center">Ação</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <?php foreach ($this->canceladas as $solicitacao) { ?>
                            <td><?= $solicitacao['id']; ?></td>
                            <td><?= $solicitacao['status']; ?></td>
                            <td class="text-center">   

                                <a href="<?php echo $this->url(array('controller' => 'produtosolicitacao', 'action' => 'resumodesolicitacao', 'solicitacaoid' => $solicitacao['id'])); ?>" class='btn btn-default btn-xs'><span class="glyphicon glyphicon-eye-open"></span> Visualizar</a>
                            </td>
                        </tr> 
                        <?php
                    }
                }
                ?>
                </tr>
            </tbody>
        </table>
    </div>     
</div>


