<h3>Lista de solicitações ativas</h3>
<hr>
<?php if ($this->listaDeSolicitacoes->current() <> null) { ?>
    <p> Abaixo seguem suas solicitações ativas, para criar seu carrinho de solicitações, selecione <b>abaixo</b> o botão <a class='btn btn-default btn-xs disabled'><span class="glyphicon glyphicon-edit"></span> Iniciar</a> para solicitar produtos, <a class='btn btn-danger btn-xs disabled'><span class="glyphicon glyphicon-remove-circle"></span> Cancelar</a> para cancelar sua solicitação ativa, ou
        <a class='btn btn-default btn-xs disabled'><span class="glyphicon glyphicon-eye-open"></span> Visualizar</a>, para visualizar os itens escolhidos.</p>
<?php } else { ?>
    <p> Você não tem ainda solicitações, mas você pode criar a sua agora mesmo, <a href="<?php echo $this->url(array('controller' => 'solicitacao', 'action' => 'inserir')); ?>">Clique aqui</a> </p>
<?php } ?>

<div class="row">
    <div class="panel panel-primary filterable">
        <div class="panel-heading">
            <span class="glyphicon glyphicon-list"></span> Lista de Solicitações
        </div>
        <table class="table table-striped table-hover">
            <tr>
                <?php if ($this->listaDeSolicitacoes->current() == null) { ?>
                <center><strong><h4>sem solicitações</h4></strong></center>
                </tr>
            <?php } else { ?>
                <thead>
                    <tr class="filters text-center">
                        <th class="text-center">Código</th>
                        <th class="text-center">Data de criação</th>
                        <th class="text-center">Status</th>
                        <th class="text-center">Ação</th>
                    </tr>
                </thead>
                <tbody>

                    <?php foreach ($this->listaDeSolicitacoes as $solicitacao) { ?>
                        <tr>
                            <td><?= $solicitacao['id']; ?></td>
                            <td><?= $solicitacao['data']; ?></td>
                            <td><?= $solicitacao['status']; ?></td>
                            <td class="text-center acao">
                                <?php if ($solicitacao['status'] == 'nova') { ?>
                                    <a class='btn btn-success btn-xs' href="<?php echo $this->url(array('controller' => 'produtosolicitacao', 'action' => 'buscarprodutosporcategoria', 'solicitacaoid' => $solicitacao['id'])); ?>"><span class="glyphicon glyphicon-shopping-cart"></span> Iniciar</a>
                                    <a href="<?php echo $this->url(array('controller' => 'solicitacao', 'action' => 'deletar', 'id' => $solicitacao['id'])); ?>" class="btn btn-danger btn-xs"><span class="glyphicon glyphicon-remove"></span> Deletar</a>
                                <?php } elseif ($solicitacao['status'] == 'entregue') { ?>

                                    <a href="<?php echo $this->url(array('controller' => 'produtosolicitacao', 'action' => 'atualizarprodutosesolicitacao', 'solicitacaoid' => $solicitacao['id'], 'status' => 'recebida', 'data_recebimento' => $data_recebimento = date("m-d-Y"))); ?>" class="btn btn-success btn-xs"><span class="glyphicon glyphicon-hand-up"></span> Recebi</a>
                                    <a href="<?php echo $this->url(array('controller' => 'produtosolicitacao', 'action' => 'resumodesolicitacao', 'solicitacaoid' => $solicitacao['id'])); ?>" class="btn btn-default btn-xs"><span class="glyphicon glyphicon-eye-open"></span> Visualizar</a>

                                <?php } else { ?>
                                    <a href="<?php echo $this->url(array('controller' => 'produtosolicitacao', 'action' => 'resumodesolicitacao', 'solicitacaoid' => $solicitacao['id'])); ?>" class='btn btn-default btn-xs'><span class="glyphicon glyphicon-eye-open"></span> Visualizar</a>
                                    <a href="<?php echo $this->url(array('controller' => 'solicitacao', 'action' => 'cancelarsolicitacao', 'solicitacaoid' => $solicitacao['id'], 'status' => 'cancelada')); ?>" class='btn btn-danger btn-xs'><span class="glyphicon glyphicon-remove-circle"></span> Cancelar</a>
                                <?php } ?>
                            </td>
                        </tr>
                        <?php
                    }
                }
                ?>
                </tr>
            </tbody>
        </table>
    </div>
</div>
