<form class="form-horizontal" action="<?= $this->baseUrl() . '/fornecedor/inserir' ?>" method="POST">
    <fieldset>
        <legend>Editar fornecedor</legend>
        <div class="lado-esquerdo">
            <div class="form-group">
                <label for="id" class="col-lg-2 control-label">CNPJ</label>
                <div class="col-lg-3">
                    <input class="form-control" id="inputId" placeholder="Ex: 397528735000" type="text" name="id" required="required" pattern="[0-9]+$" value="<?= $this->fornecedor->id ?>">
                    <span class="help-block">Somente números</span>
                </div>
            </div>
            <div class="form-group">
                <label for="razao_social" class="col-lg-2 control-label">Razão social</label>
                <div class="col-lg-4">
                    <input class="form-control" id="inputId" placeholder="Ex: Aramarinho LTDA" type="text" name="razao_social" required="true" pattern="[a-z\s]+$" value="<?= $this->fornecedor->razao_social ?>">
                    <span class="help-block">Somente letras</span>
                </div>
            </div>
            <div class="form-group">
                <label for="inputTelefone1" class="col-lg-2 control-label">Telefone Principal</label>
                <div class="col-lg-4">
                    <input class="form-control" type="tel" required="required" maxlength="15" name="telefone1" pattern="[0-9]+$" placeholder="ex: 98556452" value="<?= $this->fornecedor->telefone1 ?>"/>
                </div>
            </div>
            <div class="form-group">
                <label for="inputTelefone2" class="col-lg-2 control-label">Outro telefone</label>
                <div class="col-lg-4">
                    <input class="form-control" type="tel" maxlength="15" name="telefone2" pattern="[0-9]+$" placeholder="ex: 2124647256" value="<?= $this->fornecedor->telefone2 ?>"/>
                </div>
            </div>
        </div>
        <div class="lado-direito">
            <div class="form-group">
                <label for="rua" class="col-lg-2 control-label">Rua</label>
                <div class="col-lg-2">
                    <input type="text" class="form-control" name="rua" required="required" value="<?= $this->fornecedor->rua ?>">
                </div>
            </div>
            <div class="form-group numero">
                <label for="numero" class="col-lg-2 control-label">Nº</label>
                <div class="col-lg-4">
                    <input class="form-control" type="text" name="numero" required="true" value="<?= $this->fornecedor->numero ?>">
                </div>
            </div>
            <div class="form-group complemento">
                <div class="col-lg-8">
                    <input class="form-control" type="text" name="complemento" placeholder="Complemento" value="<?= $this->fornecedor->complemento ?>"/>
                </div>
            </div>
            <div class="form-group">
                <label for="inputBairro" class="col-lg-2 control-label">Bairro</label>
                <div class="col-lg-4">
                    <input class="form-control" type="text" required="required" name="bairro" value="<?= $this->fornecedor->bairro ?>" />
                </div>
            </div>
            <div class="form-group">
                <label for="inputMunicipio" class="col-lg-2 control-label">Município</label>
                <div class="col-lg-4">
                    <input class="form-control" type="text" name="cidade" value="<?= $this->fornecedor->cidade ?>"/>
                </div>
            </div>
            <div class="form-group uf">
                <div class="col-lg-4">
                    <input class="form-control" id="inputId" type="text"  name="estado" placeholder="uf" required="true" value="<?= $this->fornecedor->estado ?>">
                </div>
            </div>
            <div class="form-group">
                <label for="Contato" class="col-lg-2 control-label">Contato</label>
                <div class="col-lg-5">
                    <textarea class="form-control" rows="3" id="contato" name="contato" placeholder=" Ex: João Ribeiro do almoxarifado, Ramal 5378."><?= $this->fornecedor->contato ?></textarea>
                    <span class="help-block">Quais funionários você se relaciona?</span>
                </div>
            </div>
            <div class="form-group">
                <label for="Contato" class="col-lg-2 control-label">Email</label>
                <div class="col-lg-5">
                    <input type="email" required="required" class="input-text" name="email" pattern="[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,4}$" value="<?= $this->fornecedor->email ?>" />
                </div>
            </div>

        </div>
        <br><br><br>
        <div class="form-group">
            <div class="col-lg-5 col-lg-offset-5">
                <a class="btn btn-primary" href="<?php echo $this->url(array('controller' => 'fornecedor', 'action' => 'listar')); ?>">Voltar</a>
                <button type="submit" class="btn btn-success">Editar</button>
            </div>
        </div>
    </fieldset>
</form>