<form class="form-horizontal" action="<?= $this->baseUrl() . '/fornecedor/inserir' ?>" method="POST">
    <fieldset>
        <legend>Novo fornecedor</legend>
        <div class="lado-esquerdo">
            <div class="form-group">
                <label for="id" class="col-lg-2 control-label">CNPJ</label>
                <div class="col-lg-3">
                    <input class="form-control" id="inputId" placeholder="Ex: 397528735000" type="text" name="id" required="required" pattern="[0-9]+$">
                    <span class="help-block">Somente números</span>
                </div>
            </div>
            <div class="form-group">
                <label for="razao_social" class="col-lg-2 control-label">Razão social</label>
                <div class="col-lg-4">
                    <input class="form-control" id="inputId" placeholder="Ex: Aramarinho LTDA" type="text" name="razao_social" required="true" pattern="[a-z\s]+$">
                    <span class="help-block">Somente letras</span>
                </div>
            </div>
            <div class="form-group">
                <label for="inputTelefone1" class="col-lg-2 control-label">Telefone Principal</label>
                <div class="col-lg-4">
                    <input class="form-control" type="tel" required="required" maxlength="15" name="telefone1" pattern="[0-9]+$" placeholder="ex: 98556452"/>
                </div>
            </div>
            <div class="form-group">
                <label for="inputTelefone2" class="col-lg-2 control-label">Outro telefone</label>
                <div class="col-lg-4">
                    <input class="form-control" type="tel" maxlength="15" name="telefone2" pattern="[0-9]+$" placeholder="ex: 2124647256"/>
                </div>
            </div>
        </div>
        <div class="lado-direito">
            <div class="form-group">
                <label for="rua" class="col-lg-2 control-label">Rua</label>
                <div class="col-lg-2">
                    <input type="text" class="form-control" name="rua" required="required">
                </div>
            </div>
            <div class="form-group numero">
                <label for="numero" class="col-lg-2 control-label">Nº</label>
                <div class="col-lg-4">
                    <input class="form-control" type="text" name="numero" required="true">
                </div>
            </div>
            <div class="form-group complemento">
                <div class="col-lg-8">
                    <input class="form-control" type="text" placeholder="Complemento"/>
                </div>
            </div>
            <div class="form-group">
                <label for="inputTelefone1" class="col-lg-2 control-label">Bairro</label>
                <div class="col-lg-4">
                    <input class="form-control" type="text" required="required" maxlength="15" name="telefone1" pattern="[0-9]+$" placeholder="ex: 98556452"/>
                </div>
            </div>
            <div class="form-group">
                <label for="inputTelefone2" class="col-lg-2 control-label">Município</label>
                <div class="col-lg-4">
                    <input class="form-control" type="text" maxlength="15" name="telefone2" pattern="[0-9]+$" placeholder="ex: 2124647256"/>
                </div>
            </div>
            <div class="form-group uf">
                <div class="col-lg-3">
                    <input class="form-control" id="inputId" type="text"  name="estado" placeholder="uf" required="true">
                </div>
            </div>
            <div class="form-group">
                <label for="Contato" class="col-lg-2 control-label">Contato</label>
                <div class="col-lg-5">
                    <textarea class="form-control" rows="3" id="descricao" name="descricao" placeholder=" Ex: João Ribeiro do almoxarifado, Ramal 5378."></textarea>
                    <span class="help-block">Quais funionários você se relaciona?</span>
                </div>
            </div>
        </div>
        <br><br><br>
        <div class="form-group">
            <div class="col-lg-5 col-lg-offset-5">
                <a class="btn btn-primary" href="<?php echo $this->url(array('controller' => 'funcionario', 'action' => 'listar')); ?>">Voltar</a>
                <button type="submit" class="btn btn-success">Criar</button>
            </div>
        </div>
    </fieldset>
</form>