<legend>Fornecedores cadastrados</legend>
<hr>
<div class="panel panel-primary"> 

   <div class="panel-heading" id="actions"><span class="glyphicon glyphicon-list"></span> Lista de funcionários cadastrados
      <a href="<?php echo $this->url(array('controller' => 'fornecedor', 'action' => 'inserir')); ?>" class="btn btn-info btn-xs pull-right" style="border:2"><span class="glyphicon glyphicon-plus"></span>Novo usuário</a>
   </div>
    <div class="panel-body">
        <table class="table table-striped table-hover tabela-fornecedor"> 
            <thead>
                <tr>
                    <th>Cnpj</th>
                    <th>Razão Social</th>
                    <th>Telefone principal</th>
                    <th>Outro contato</th>
                    <th>Rua</th>
                    <th>Número</th>
                    <th>Complemento</th>
                    <th>Bairro</th>
                    <th>Cep</th>
                    <th>Cidade</th>
                    <th>Estado</th>
                    <th>Contato</th>
                    <th>Email</th>
                    <th>Referência</th>
                </tr>
            </thead>
            <tr>
                <?php
                foreach ($this->listaDeFornecedores as $fornecedor) { ?>
                    <td><?= $fornecedor['id']; ?></td>
                    <td><?= $fornecedor['razao_social'];?></td>
                     <td><?= $fornecedor['telefone1'];?></td>
                    <td><?= $fornecedor['telefone2'];?></td>
                    <td><?= $fornecedor['rua'];?></td>
                    <td><?= $fornecedor['numero'];?></td>
                    <td><?= $fornecedor['complemento'];?></td>
                    <td><?= $fornecedor['bairro'];?></td>
                    <td><?= $fornecedor['cep'];?></td>
                    <td><?= $fornecedor['cidade'];?></td>
                    <td><?= $fornecedor['estado'];?></td>
                    <td><?= $fornecedor['contato'];?></td>
                    <td><?= $fornecedor['email'];?></td>
                    <td><?= $fornecedor['referencia'];?></td>
                    <td class="text-center"><a class='btn btn-block btn-warning btn-xs' href="<?php echo $this->url(array('controller' => 'fornecedor', 'action' => 'editar', 'id' => $fornecedor['id'])); ?>"><span class="glyphicon glyphicon-edit"></span>Editar</a></td>
                        <td class="text-center"><a href="<?php echo $this->url(array('controller' => 'fornecedor', 'action' => 'deletar', 'id' => $fornecedor['id'])); ?>" class="btn btn-block btn-danger btn-xs"><span class="glyphicon glyphicon-remove-circle"></span>Excluir</a>
                    </td>
               
                </tr>     
      <?php } ?>
        </table>
    </div>
</div>

