<div class="panel "> <div class="panel-heading panel-primary">
        <div id="actions">
            <a href="<?php echo $this->url(array('controller' => 'perfil', 'action' => 'inserir')); ?>" class="btn btn-primary btn-xs pull left"><b>+</b>Novo perfil</a>
        </div>                
        <center><h3 class="panel-title">>> Lista de perfis cadastrados <<</h3></center>
    </div>
    <div class="panel-body">
        <table class="table table-striped table-hover"> 
            <thead>
                <tr>
                    <th>Código</th>
                    <th>Nome</th>
                    <th>Descrição</th>
                    <th class="text-center">Ação</th>
                </tr>
            </thead>
            <tr>
                <?php foreach ($this->listaDePerfis as $perfil) { ?>
                    <td><?= $perfil['id']; ?></td>
                    <td><?= $perfil['nome']; ?></td>
                    <td><?= $perfil['descricao']; ?></td>
                    <td class="text-center"><a class='btn btn-info btn-xs' href="<?php echo $this->url(array('controller' => 'perfil', 'action' => 'editar', 'id' => $perfil['id'])); ?>"><span class="glyphicon glyphicon-edit"></span>Editar</a>
                        <a href="<?php echo $this->url(array('controller' => 'perfil', 'action' => 'deletar', 'id' => $perfil['id'])); ?>" class="btn btn-danger btn-xs"><span class="glyphicon glyphicon-remove"></span>Deletar</a>
                    </td>
                </tr>     
            <?php } ?>      
        </table>
    </div>
</div>