<h3>Lista de devoluções concretizadas</h3>
<hr>
<?php if ($this->devolucoesantigas <> null) { ?>
    <p> Abaixo seguem suas devoluções finalizadas. </p>
<?php } else { ?>
    <p> Você não tem ainda devoluções concretizadas, porisso seu histórico encontra-se vazio.</a> </p>
<?php } ?>

<div class="row">
    <div class="panel panel-primary filterable">
        <div class="panel-heading">
            <span class="glyphicon glyphicon-list"></span> Histórico
        </div>
        <table class="table table-striped table-hover ">
            <tr>
                <?php if ($this->devolucoesantigas == null) { ?>
                <center><strong><h4>sem devoluções concretizadas</h4></strong></center>
                </tr>
            <?php } else { ?>
                <thead>
                    <tr class="filters">
                        <th class="text-center">Solicitacao</th>
                        <th class="text-center">Status</th>
                        <th class="text-center">Data da devolução</th>  
                        <th class="text-center">Produto</th>  
                        <th class="text-center">Quantidade devolvida</th>  
                    </tr>
                </thead>
                <tbody>
                    <tr>

                        <?php
                        foreach ($this->devolucoesantigas as $devolucao) {
                            ?>
                            <td><?= $devolucao['solicitacaoid']; ?></td>
                            <td><?= $devolucao['status_devolucao']; ?></td>
                            <td><?= $devolucao['data_devolucao']; ?></td>
                            <?php
                            $tProduto = new Produto;
                            $produto = $tProduto->findProdutoById($devolucao['produtoid']);
                            $nomeProduto = $produto->current()->nome;
                            ?>
                            <td><?= $nomeProduto; ?></td>
                            <td><?= $devolucao['quantidade_devolvida']; ?></td>
                            <?php $login = Zend_Auth::getInstance()->getIdentity()->login; ?>
                        </tr>
                        <?php
                    }
                }
                ?>
                </tr>
            </tbody>
        </table>
    </div>     
</div>


