<form class="form-horizontal" action="<?= $this->baseUrl() . '/funcao/editar' ?>" method="POST">
    <fieldset>
        <legend>Editando uma função</legend>
        <input type="hidden" name="id" value="<?php echo $this->funcao->id ?>">
        <div class="form-group">
            <label for="select" class="col-lg-2 control-label">Setor</label>
            <div class="col-lg-10">
                <select class="form-control" id="select" name="setorid">
                    <option></option>
                    <?php foreach ($this->setores as $nomeSetor): ?> 
                        <option value="<?php echo $nomeSetor['id']; ?>"><?php echo $nomeSetor['nome']; ?></option> 
                        <?php
                    endforeach;
                    ?> 
                </select>     
                <br>
            </div>
        </div>
        <div class="form-group">
            <label for="inputNome" class="col-lg-2 control-label">Nome</label>
            <div class="col-lg-10">        
                <input class="form-control" id="inputNome" placeholder="" type="text" name="nome" value="<?php echo $this->funcao->nome ?>">
            </div>
        </div>    
        <div class="form-group">
            <label for="Descrição" class="col-lg-2 control-label">Descrição</label>
            <div class="col-lg-10">
                <textarea class="form-control" rows="3" id="descricao" name="descricao"><?php echo $this->funcao->descricao ?></textarea>
                <span class="help-block">Faça uma breve descrição sobre o setor a ser editado</span>
            </div>
        </div>    
        <div class="form-group">
            <div class="col-lg-10 col-lg-offset-2">

                <button type="submit" class="btn btn-primary">Editar</button>
            </div>
        </div>
    </fieldset>
</form>
<a href="<?php echo $this->url(array('controller' => 'funcao', 'action' => 'listar')); ?>"><button class="btn btn-default">Voltar</button></a>