<form class="form-horizontal" action="<?= $this->baseUrl() . '/funcao/inserir' ?>" method="POST">
    <fieldset>
        <legend>Criando nova função</legend>
        <div class="form-group">
            <label for="select" class="col-lg-2 control-label">Setor</label>
            <div class="col-lg-10">
                <select required="true" class="form-control" id="select" name="setorid">
                    <option value="">--selecione</option>
                    <?php foreach ($this->setores as $nomeSetor): ?> 
                        <option value="<?php echo $nomeSetor['id']; ?>"><?php echo $nomeSetor['nome']; ?></option> 
                        <?php
                    endforeach;
                    ?> 
                </select>     
                <br>
            </div>
        </div>
        <div class="form-group">
            <label for="inputNome" class="col-lg-2 control-label">Nome</label>
            <div class="col-lg-10">
                <input class="form-control" id="inputNome" placeholder="" type="text" name="nome">
            </div>
        </div>    
        <div class="form-group">
            <label for="Descrição" class="col-lg-2 control-label">Descrição</label>
            <div class="col-lg-10">
                <textarea class="form-control" rows="3" id="descricao" name="descricao"></textarea>
                <span class="help-block">Faça uma breve descrição sobre o funcao a ser criado</span>
            </div>
        </div>    
        <div class="form-group">
            <div class="col-lg-10 col-lg-offset-2">
                <!--        <button class="btn btn-default">Cancelar</button>-->
                <a href="<?php echo $this->url(array('controller' => 'funcao', 'action' => 'listar')); ?>">Voltar</a>
                <button type="submit" class="btn btn-primary">Inserir</button>
            </div>
        </div>
    </fieldset>
</form>