<div class="panel "> <div class="panel-heading panel-primary">
        <div id="actions">
            <a href="<?php echo $this->url(array('controller' => 'funcao', 'action' => 'inserir')); ?>" class="btn btn-primary btn-xs pull left"><b>+</b>Nova função</a>
        </div>  
        <center><h3 class="panel-title">>> Lista de funções cadastradas <<</h3></center>
    </div>
    <div class="panel-body">
        <table class="table table-striped table-hover">               
            <thead>
                <tr>
                    <th>Setor</th>
                    <th>Nome</th>
                    <th>Descrição</th>
                    <th class="text-center">Ação</th>
                </tr>
            </thead>
            <tr>
                <?php
                foreach ($this->listaDeFuncoes as $funcao) {

                    $tSetor = new Setor();
                    $setorNome = $tSetor->findSetorById($funcao['id']);
                    ?>
                    <td><?= $setorNome['nome']->nome; ?></td>
                    <td><?= $funcao['nome']; ?></td>
                    <td><?= $funcao['descricao']; ?></td>
                    <td class="text-center"><a class='btn btn-info btn-xs' href="<?php echo $this->url(array('controller' => 'funcao', 'action' => 'editar', 'id' => $funcao['id'])); ?>"><span class="glyphicon glyphicon-edit"></span>Editar</a>
                        <a href="<?php echo $this->url(array('controller' => 'funcao', 'action' => 'deletar', 'id' => $funcao['id'])); ?>" class="btn btn-danger btn-xs"><span class="glyphicon glyphicon-remove"></span>Deletar</a>
                    </td>
                </tr>     
            <?php } ?>      
        </table>
    </div>
</div>