<form class="form-horizontal" action="<?= $this->baseUrl() . '/setor/editar'?>" method="POST">
  <fieldset>
    <legend>Editando um setor</legend>
    <input type="hidden" name="id" value="<?php echo $this->setor->id?>">
    <div class="form-group">
      <label for="inputNome" class="col-lg-2 control-label">Nome</label>
      <div class="col-lg-10">        
        <input class="form-control" id="inputNome" placeholder="" type="text" name="nome" value="<?php echo $this->setor->nome?>">
      </div>
    </div>    
    <div class="form-group">
      <label for="Descrição" class="col-lg-2 control-label">Descrição</label>
      <div class="col-lg-10">
        <textarea class="form-control" rows="3" id="descricao" name="descricao"><?php echo $this->setor->descricao?></textarea>
        <span class="help-block">Faça uma breve descrição sobre o setor a ser criado</span>
      </div>
    </div>    
    <div class="form-group">
      <div class="col-lg-10 col-lg-offset-2">

        <button type="submit" class="btn btn-primary">Editar</button>
      </div>
    </div>
  </fieldset>
</form>
<a href="<?php echo $this->url(array('controller' => 'setor', 'action' => 'listar')); ?>"><button class="btn btn-default">Voltar</button></a>