<div class="panel "> <div class="panel-heading panel-primary">
    <div id="actions">
        <a href="<?php echo $this->url(array('controller' => 'setor', 'action' => 'inserir')); ?>" class="btn btn-primary btn-xs pull left"><b>+</b>Novo setor</a>
    </div>                
        <center><h3 class="panel-title">>> Lista de setores cadastrados <<</h3></center>
    </div>
    <div class="panel-body">
        <table class="table table-striped table-hover"> 
            <thead>
            <tr>
                <th>Código</th>
                <th>Nome</th>
                <th>Descrição</th>
                <th class="text-center">Ação</th>
            </tr>
            </thead>
                <tr>
                    <?php foreach ($this->listaDeSetores as $setor) { ?>
                    <td><?= $setor['id']; ?></td>
                    <td><?= $setor['nome']; ?></td>
                    <td><?= $setor['descricao']; ?></td>
                    <td class="text-center"><a class='btn btn-info btn-xs' href="<?php echo $this->url(array('controller' => 'setor', 'action' => 'editar', 'id' => $setor['id'])); ?>"><span class="glyphicon glyphicon-edit"></span>Editar</a>
                    <a href="<?php echo $this->url(array('controller' => 'setor', 'action' => 'deletar', 'id' => $setor['id'])); ?>" class="btn btn-danger btn-xs"><span class="glyphicon glyphicon-remove"></span>Deletar</a>
                    </td>
                </tr>     
            <?php } ?>      
        </table>
    </div>
</div>