<h3>Aprovação parcial de item</h3>
<hr>
<div class="instrucao">
    <p>Insira a quantidade que deseja aprovar e informe uma observação se achar necessário</p>
    <form class="form-horizontal" action="" method="POST">
        <input type="hidden" name="produtoid" value="<?php echo $this->produtoid ?>">
        <input type="hidden" name="solicitacaoid" value="<?php echo $this->solicitacaoid ?>">
        <br><br>
            <div class="form-group">
                <div class="col-lg-5 col-lg-offset-5">
                    <legend>Aprovando um item</legend>
                    <input type="text" name="quantidade" placeholder="Quantidade a aprovar">
                </div>
            </div>    
            <div class="form-group">
                <div class="col-lg-5 col-lg-offset-5">
                    <input type="textarea" name="observacao" placeholder="Informe se achar necessário">
                </div>
            </div>    
            <div class="form-group">
                <div class="col-lg-5 col-lg-offset-5">
                    <!--        <button class="btn btn-default">Cancelar</button>-->
                    <a href="<?php echo $this->url(array('controller' => 'solicitacao', 'action' => 'listargerente')); ?>">Voltar</a>
                    <button type="submit" class="btn btn-primary">Aprovar</button>
                </div>
            </div>
    </form>

</div>








