<div class="carrinho">    
    <div class="carrinho panel panel-primary">
        <div class="panel-heading">
            <div class="panel-title">
                <div class="row">
                    <div class="col-xs-6">
                        <h5><span class="glyphicon glyphicon-shopping-cart"></span> Carrinho de Solicitações</h5>
                    </div>
                    <div class="col-xs-6">
                        <a class='btn btn-primary btn-sm btn-block' href="<?php echo $this->url(array('controller' => 'produtosolicitacao', 'action' => 'buscarprodutosporcategoria')); ?>"><span class="glyphicon glyphicon-share-alt"></span>Continue escolhendo</a> 
                    </div>
                </div>
            </div>
        </div>
        <div class="panel-body">

            <form action="<?= $this->baseUrl() . '/produtosolicitacao/atualizarprodutosesolicitacao' ?>" method="POST">

                <?php if ($this->conteudoDoCarrinho->current() == null) { ?>
                    <br>
                    <center><strong><h4>Você ainda não escolheu produtos para esta solicitação, clique em "Continue escolhendo".</h4></strong></center>
                    <?php
                } else {
                    $temRegistro = "true";
                    foreach ($this->conteudoDoCarrinho as $item) {

                        $tProduto = new Produto();
                        $produto = $tProduto->findProdutoById($item->produtoid);
                        ?>

                        <div class="row linhaCarrinhoSolicitacao">
                            <br>
                            <div class="col-xs-6 produtoCart">
                                <input type="hidden" name="produto[]" value="<?= $item->produtoid ?>"/>                                                                   
                                <input type="hidden" name="solicitacaoid" value="<?php echo $this->solicitacaoid ?>"/>       
                                <h4 class="product-name"><strong><?php echo $produto[0]->nome; ?> <small class="label label-warning"> <b class="disponiveis"><?php echo $produto->current()->quantidade ?></b> itens disponíveis</small></h4>
                                <br>    
                            </div>
                            <div class="col-xs-3">
                                <div class="col-xs-6 text-right">
                                    <h6>Qtd</h6>
                                </div>
                                <div class="col-xs-4">
                                    <input type="number" max ="" min="1" placeholder="1" class="form-control input-sm quantidadeSolicitada" name = "quantidade[]">
                                </div>
                                <div class="col-xs-2">
                                    <a class="btn btn-link btn-xs" href="<?php echo $this->url(array('controller' => 'produtosolicitacao', 'action' => 'deletaritemdocarrinho', 'solicitacaoid' => $this->solicitacaoid, 'produtoid' => $item->produtoid)); ?>"><span class="glyphicon glyphicon-trash"> </span></a>    
                                </div>
                            </div>

                        </div>
                        <hr>
                        <?php
                    }
                }
                ?>
                <hr>
                <div class="row">
                    <div class="col-xs-12">
                        <?php if ($temRegistro) { ?>
                            <button id="moverProCarrinhoSolicitacao" class="btn btn-success btn-xs">
                                <span class="glyphicon glyphicon-send"></span> Enviar solicitação
                            </button>
                        <?php } ?>
                    </div>
                </div>
            </form>
        </div>
        <?php if ($temRegistro) { ?>
            <div class="panel-footer">
                <td class="text-center"><a class='btn btn-danger btn-xs' href="<?php echo $this->url(array('controller' => 'produtosolicitacao', 'action' => 'limparcarrinhodesolicitacao', 'solicitacaoid' => $this->solicitacaoid)); ?>"><span class="glyphicon glyphicon-floppy-remove"></span> Esvaziar carrinho</a> 
                <?php } ?>
        </div>
    </div>
</div>