<h3>Cadastro de agendamento</h3>
<hr>
<div class="instrucao">
    <p>Insira uma data limite que deseja receber seu produto e a quantidade de itens que precisar. Após, clique em "agendar" para finalizar seu agendamento</p>
    <form class="form-horizontal" action="<?= $this->baseUrl() . '/produtosolicitacao/inserirprodutoemsolicitacaoagendada' ?>" method="POST">
        <input type="hidden" name="produtoid" value="<?php echo $this->produtoid ?>">
        <br><br>
            <div class="form-group">
                <div class="col-lg-5 col-lg-offset-5">
                    <legend>Agendando seu produto</legend>
                    <input type="text" name="data_agendamento" placeholder="Data de Agendamento">
                </div>
            </div>    
            <div class="form-group">
                <div class="col-lg-5 col-lg-offset-5">
                    <input type="text" name="quantidade" placeholder="Quantidade">
                </div>
            </div>    
            <div class="form-group">
                <div class="col-lg-5 col-lg-offset-5">
                    <!--        <button class="btn btn-default">Cancelar</button>-->
                    <a href="<?php echo $this->url(array('controller' => 'solicitacao', 'action' => 'deletaragendada')); ?>">Vosssltar</a>
                    <button type="submit" class="btn btn-primary">Agendar</button>
                </div>
            </div>
    </form>

</div>








