<h3>Agendar produto</h3>
<hr>
<div class="instrucao">
    Para agendar o produto, escolha a data que deseja receber o produto, insira a quantidade necessária e clique em Agendar. Caso queira voltar ao menu anterior, clique <a href="<?php echo $this->url(array('controller' => 'solicitacao', 'action' => 'deletaragendada')); ?>">Aqui</a>.</p>
    <form class="form-horizontal" action="<?= $this->baseUrl() . '/produtosolicitacao/inserirprodutoemsolicitacaoagendada' ?>" method="POST">
        <input type="hidden" name="produtoid" value="<?php echo $this->produtoid ?>">
        <br><br>
             <div class="form-group">
                <div class="col-lg-3  col-lg-offset-4">
                    <input class="form-control" id="data_agendamento" type="date" required="true" value="" name="data_agendamento" placeholder="Data de agendamento">
                 </div>   
                 <div class="col-lg-1">
                    <input class="form-control" id="quantidade" required="true" type="number" name="quantidade" min="1" value="1">
                </div>
            </div>       
            <div class="form-group">
                <div class="col-lg-4 col-lg-offset-4">
                    <button type="submit" class="btn btn-success btn-block"><span class="glyphicon glyphicon-calendar"></span> Agendar</button>
                </div>
            </div>
    </form>

</div>




