<?php var_dump($this->devolucoesantigas);die; ?>
<h3>Lista de devoluções concretizadas</h3>
<hr>
<?php if ($this->devolucoesantigas <> null) { ?>
<p> Abaixo seguem suas devoluções finalizadas. </p>
<?php } else { ?>
    <p> Você não tem ainda devoluções concretizadas, porisso seu histórico encontra-se vazio.</a> </p>
<?php } ?>

<div class="row">
    <div class="panel panel-primary filterable">
        <div class="panel-heading">
            <span class="glyphicon glyphicon-list"></span>Histórico
        </div>
        <table class="table">
            <tr>
                <?php if ($this->devolucoesantigas == null) { ?>
                <center><strong><h4>sem devoluções concretizadas</h4></strong></center>
                </tr>
            <?php } else { ?>
                <thead>
                    <tr class="filters">
                    <th><input type="text" class="form-control" placeholder="Solicitação" disabled></th>
                    <th><input type="text" class="form-control" placeholder="Solicitante" disabled></th>
                    <th><input type="text" class="form-control" placeholder="Data de devolução" disabled></th>  
                    <th><input type="text" class="form-control" placeholder="Produto" disabled></th>  
                    <th><input type="text" class="form-control" placeholder="Quantidade devolvida" disabled></th>  
                    <th class="text-center">Ação</th>
                </tr>
                </thead>
                <tbody>
                    <tr>
                    
                    <?php foreach ($this->devolucoesantigas as $devolucao) { 
                        $tUsuario = new Usuario();
                        $login = $tUsuario->findUsuarioById($devolucao['usuarioid'])->current()->login;
                    ?>
                        <td><?= $devolucao['solicitacaoid']; ?></td>
                        <td><?= $login; ?></td>
                        <td><?= $devolucao['data_devolucao']; ?></td>
                        <?php $tProduto = new Produto;
                              $produto = $tProduto->findProdutoById($devolucao['produtoid']);
                              $nomeProduto = $produto->current()->nome;?>
                        <td><?= $nomeProduto; ?></td>
                        <td><?= $devolucao['quantidade_devolvida']; ?></td>
                        <?php $login = Zend_Auth::getInstance()->getIdentity()->login; ?>
                        <td class="text-center">
                           <a href="<?php echo $this->url(array('controller' => 'produtosolicitacao', 'action' => 'resumodesolicitacao', 'solicitacaoid' => $devolucao['id'])); ?>" class="btn btn-default btn-xs"><span class="glyphicon glyphicon-ok"></span>Visualizar</a>
                        </td>
                    </tr> 
                    <?php }
                }
                ?>
                </tr>
            </tbody>
        </table>
    </div>     
</div>


