    <h3>Resumo da solicitação</h3>
    <hr>
    <p> Abaixo segue o resumo de sua solicitação, selecione <a href="">Voltar</a> para retornar ao histórico</p>
     <div class="row">
        <div class="panel panel-primary filterable">
            <div class="panel-heading">
                <span class="glyphicon glyphicon-list"></span>Resumo da solicitção
            </div>            
                <thead>
                <tr class="filters">
                    <th><input type="text" class="form-control" placeholder="Código" disabled></th>
                    <th><input type="text" class="form-control" placeholder="Data" disabled></th>
                    <th><input type="text" class="form-control" placeholder="Status" disabled></th>  
                </tr>
                </thead>
                <tbody>
                <tr>
                   <?php foreach ($this->resumoDeSolicitacao as $solicitacao) { ?>
                        <td><?= $solicitacao['id']; ?></td>
                        <td><?= $solicitacao['data']; ?></td>
                        <td><?= $solicitacao['status']; ?></td>
                 </tr>
                    <?php  } ?>
                </tr>
                </tbody>
            </table>
        </div>     
    </div>


