<h3>Resumo da solicitação</h3>
<?php 
$tSolicitacao = new DbTable_Solicitacao;
      $solicitacao = $tSolicitacao->find($this->resumoDeSolicitacao[0]->solicitacaoid);
      if ($solicitacao->current()->status == 'recebida'){?>
<hr>
<p> Abaixo segue o resumo de sua solicitação já finalizada, <a href="<?php echo $this->url(array('controller' => 'solicitacao', 'action' => 'listarhistorico')); ?>">clique aqui</a> e retorne ao histórico de solicitações.</p>
      <?php }elseif ($solicitacao->current()->status == 'em analise' || $solicitacao->current()->status == 'aprovada'){ ?>
<p> Abaixo segue o resumo de sua solicitação ainda não finalizada, selecione <a href="<?php echo $this->url(array('controller' => 'solicitacao', 'action' => 'listar')); ?>">Voltar</a> para retornar para sua lista de solicitações.</p>
      <?php } ?>
<div class="row">
    <div class="panel panel-primary filterable">
        <div class="panel-heading">
            <span class="glyphicon glyphicon-list"></span>Resumo da solicitção
        </div>
        <table class="table">
            <thead>
            <tr>
                <th>Solicitação</th>
                <th>Data da solicitação</th>
                <?php if ($solicitacao->current()->status == 'agendada' || $solicitacao->current()->status == 'pendente'){?>
                <th>Data de agendametno</th>                
                <?php }elseif($solicitacao->current()->status == 'reprovada'){ ?>
                <th>Data de Reprovação</th>
                <?php }else{ ?>
                <th>Data de aprovação</th>
                <th>Data de recebimento</th>
                <?php } ?>
            </tr>
            </thead>
            <tbody>
            <tr>
                <?php foreach ($this->resumoDeSolicitacao as $produtosolicitacao) { ?>

                    <?php
                    $tSolicitacao = new DbTable_Solicitacao();
                    $solicitacao = $tSolicitacao->find($produtosolicitacao['solicitacaoid']);
                    ?>

                    <td><?= $produtosolicitacao['solicitacaoid']; ?></td>
                    <td><?= $solicitacao->current()->data; ?></td>
                       <?php if ($solicitacao->current()->status == 'agendada' || $solicitacao->current()->status == 'pendente'){?>
                <td><?= $solicitacao->current()->data_agendamento; ?></td>                
                 <?php }elseif($solicitacao->current()->status == 'reprovada'){ ?>                 
                <td><?= $solicitacao->current()->data_atualizacao_status?></td>
                <?php }else{ ?>
                  <td><?= $solicitacao->current()->data_aprovacao; ?></td>
                    <td><?= $solicitacao->current()->data_recebimento; ?></td>  
                    
                <?php }}?>
            </tr>
            <?php if (!empty($solicitacao->current()->observacao)){?>
            <tr>
                <th>Observação</th>
            </tr>
          <?php  }?>
            <tr>
                 
                <td>
                    <?php  
                    $login = Zend_Auth::getInstance()->getIdentity()->login; 
                    if ($solicitacao->current()->status == 'agendada' || $solicitacao->current()->status == 'pendente'){?>
                        <a href="<?php echo $this->url(array('controller' => 'solicitacao', 'action' => 'inserirobservacao', 'solicitacaoid' => $solicitacao->current('id')->id, 'status' => 'pendente','data_atualizacao_status' => $data_atualizacao_status = date("m-d-Y"), 'gerente_responsavel' => $login)); ?>" <span class="glyphicon glyphicon-plus"></span>Atualizar</a>
                    <?php } ?>
                <?= $solicitacao->current()->observacao; ?> 
                </td>
                 
            </tr>
            <table>
                <thead>
                <tr>
                    <th>Produto</th>
                    <th>Quantidade</th>
                </tr>
                </thead>
                <br><br><br>
                <tr  ><h4 class="text-center">Produtos escolhidos nesta solicitação:</h4></tr>
                <br>
                <div class="col-lg-4">
                    <tbody>
                    <tr>
                        <?php
                        $tProduto = new DbTable_Produto();
                        $produto = $tProduto->find($produtosolicitacao['produtoid']);

                        $tProdutosolicitacao = new Produtosolicitacao();
                        $produtosolicitacao = $tProdutosolicitacao->findByProdutoESolicitacao($produtosolicitacao['solicitacaoid'], $produtosolicitacao['produtoid']);
                        ?>

                        <td style="width: 300px;"><?= $produto->current()->nome; ?></td>
                        <td><?= $produtosolicitacao->current()->quantidade; ?></td>
                    </tr>
                    </tbody>
                </div>
            </table>

            </tbody>
        </table>
    </div>
</div>


